/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_AdditionalRACH_Config_r17_H_
#define	_AdditionalRACH_Config_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RACH_ConfigCommon;
struct MsgA_ConfigCommon_r16;

/* AdditionalRACH-Config-r17 */
typedef struct AdditionalRACH_Config_r17 {
	struct RACH_ConfigCommon	*rach_ConfigCommon_r17;	/* OPTIONAL */
	struct MsgA_ConfigCommon_r16	*msgA_ConfigCommon_r17;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AdditionalRACH_Config_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdditionalRACH_Config_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_AdditionalRACH_Config_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_AdditionalRACH_Config_r17_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RACH-ConfigCommon.h"
#include "MsgA-ConfigCommon-r16.h"

#endif	/* _AdditionalRACH_Config_r17_H_ */
#include <asn_internal.h>
