/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_AvailabilityCombinationsPerCell_r16_H_
#define	_AvailabilityCombinationsPerCell_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AvailabilityCombinationsPerCellIndex-r16.h"
#include "CellIdentity.h"
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct AvailabilityCombination_r16;
struct AvailabilityCombinationRB_Groups_r17;

/* AvailabilityCombinationsPerCell-r16 */
typedef struct AvailabilityCombinationsPerCell_r16 {
	AvailabilityCombinationsPerCellIndex_r16_t	 availabilityCombinationsPerCellIndex_r16;
	CellIdentity_t	 iab_DU_CellIdentity_r16;
	long	*positionInDCI_AI_r16;	/* OPTIONAL */
	struct AvailabilityCombinationsPerCell_r16__availabilityCombinations_r16 {
		A_SEQUENCE_OF(struct AvailabilityCombination_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} availabilityCombinations_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct AvailabilityCombinationsPerCell_r16__ext1 {
		struct AvailabilityCombinationsPerCell_r16__ext1__availabilityCombinationsRB_Groups_r17 {
			A_SEQUENCE_OF(struct AvailabilityCombinationRB_Groups_r17) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *availabilityCombinationsRB_Groups_r17;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct AvailabilityCombinationsPerCell_r16__ext2 {
		long	*positionInDCI_AI_RBGroups_v1720;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AvailabilityCombinationsPerCell_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AvailabilityCombinationsPerCell_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_AvailabilityCombinationsPerCell_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_AvailabilityCombinationsPerCell_r16_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "AvailabilityCombination-r16.h"
#include "AvailabilityCombinationRB-Groups-r17.h"

#endif	/* _AvailabilityCombinationsPerCell_r16_H_ */
#include <asn_internal.h>
