/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_BandCombination_UplinkTxSwitch_r16_H_
#define	_BandCombination_UplinkTxSwitch_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "BandCombination.h"
#include <NativeEnumerated.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BandCombination_UplinkTxSwitch_r16__uplinkTxSwitching_OptionSupport_r16 {
	BandCombination_UplinkTxSwitch_r16__uplinkTxSwitching_OptionSupport_r16_switchedUL	= 0,
	BandCombination_UplinkTxSwitch_r16__uplinkTxSwitching_OptionSupport_r16_dualUL	= 1,
	BandCombination_UplinkTxSwitch_r16__uplinkTxSwitching_OptionSupport_r16_both	= 2
} e_BandCombination_UplinkTxSwitch_r16__uplinkTxSwitching_OptionSupport_r16;
typedef enum BandCombination_UplinkTxSwitch_r16__uplinkTxSwitching_PowerBoosting_r16 {
	BandCombination_UplinkTxSwitch_r16__uplinkTxSwitching_PowerBoosting_r16_supported	= 0
} e_BandCombination_UplinkTxSwitch_r16__uplinkTxSwitching_PowerBoosting_r16;
typedef enum BandCombination_UplinkTxSwitch_r16__ext1__uplinkTxSwitching_PUSCH_TransCoherence_r16 {
	BandCombination_UplinkTxSwitch_r16__ext1__uplinkTxSwitching_PUSCH_TransCoherence_r16_nonCoherent	= 0,
	BandCombination_UplinkTxSwitch_r16__ext1__uplinkTxSwitching_PUSCH_TransCoherence_r16_fullCoherent	= 1
} e_BandCombination_UplinkTxSwitch_r16__ext1__uplinkTxSwitching_PUSCH_TransCoherence_r16;

/* Forward declarations */
struct BandCombination_v1540;
struct BandCombination_v1560;
struct BandCombination_v1570;
struct BandCombination_v1580;
struct BandCombination_v1590;
struct BandCombination_v1610;
struct ULTxSwitchingBandPair_r16;

/* BandCombination-UplinkTxSwitch-r16 */
typedef struct BandCombination_UplinkTxSwitch_r16 {
	BandCombination_t	 bandCombination_r16;
	struct BandCombination_v1540	*bandCombination_v1540;	/* OPTIONAL */
	struct BandCombination_v1560	*bandCombination_v1560;	/* OPTIONAL */
	struct BandCombination_v1570	*bandCombination_v1570;	/* OPTIONAL */
	struct BandCombination_v1580	*bandCombination_v1580;	/* OPTIONAL */
	struct BandCombination_v1590	*bandCombination_v1590;	/* OPTIONAL */
	struct BandCombination_v1610	*bandCombination_v1610;	/* OPTIONAL */
	struct BandCombination_UplinkTxSwitch_r16__supportedBandPairListNR_r16 {
		A_SEQUENCE_OF(struct ULTxSwitchingBandPair_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} supportedBandPairListNR_r16;
	long	*uplinkTxSwitching_OptionSupport_r16;	/* OPTIONAL */
	long	*uplinkTxSwitching_PowerBoosting_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct BandCombination_UplinkTxSwitch_r16__ext1 {
		long	*uplinkTxSwitching_PUSCH_TransCoherence_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BandCombination_UplinkTxSwitch_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_uplinkTxSwitching_OptionSupport_r16_11;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_uplinkTxSwitching_PowerBoosting_r16_15;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_uplinkTxSwitching_PUSCH_TransCoherence_r16_19;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_BandCombination_UplinkTxSwitch_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_BandCombination_UplinkTxSwitch_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_BandCombination_UplinkTxSwitch_r16_1[11];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "BandCombination-v1540.h"
#include "BandCombination-v1560.h"
#include "BandCombination-v1570.h"
#include "BandCombination-v1580.h"
#include "BandCombination-v1590.h"
#include "BandCombination-v1610.h"
#include "ULTxSwitchingBandPair-r16.h"

#endif	/* _BandCombination_UplinkTxSwitch_r16_H_ */
#include <asn_internal.h>
