/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_BandParametersSidelinkEUTRA_NR_r16_H_
#define	_BandParametersSidelinkEUTRA_NR_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#include "BandParametersSidelink-r16.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BandParametersSidelinkEUTRA_NR_r16_PR {
	BandParametersSidelinkEUTRA_NR_r16_PR_NOTHING,	/* No components present */
	BandParametersSidelinkEUTRA_NR_r16_PR_eutra,
	BandParametersSidelinkEUTRA_NR_r16_PR_nr
} BandParametersSidelinkEUTRA_NR_r16_PR;

/* BandParametersSidelinkEUTRA-NR-r16 */
typedef struct BandParametersSidelinkEUTRA_NR_r16 {
	BandParametersSidelinkEUTRA_NR_r16_PR present;
	union BandParametersSidelinkEUTRA_NR_r16_u {
		struct BandParametersSidelinkEUTRA_NR_r16__eutra {
			OCTET_STRING_t	*bandParametersSidelinkEUTRA1_r16;	/* OPTIONAL */
			OCTET_STRING_t	*bandParametersSidelinkEUTRA2_r16;	/* OPTIONAL */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *eutra;
		struct BandParametersSidelinkEUTRA_NR_r16__nr {
			BandParametersSidelink_r16_t	 bandParametersSidelinkNR_r16;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BandParametersSidelinkEUTRA_NR_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BandParametersSidelinkEUTRA_NR_r16;
extern asn_CHOICE_specifics_t asn_SPC_BandParametersSidelinkEUTRA_NR_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_BandParametersSidelinkEUTRA_NR_r16_1[2];
extern asn_per_constraints_t asn_PER_type_BandParametersSidelinkEUTRA_NR_r16_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _BandParametersSidelinkEUTRA_NR_r16_H_ */
#include <asn_internal.h>
