/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_BandCombination_v1700_H_
#define	_BandCombination_v1700_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CA_ParametersNR_v1700;
struct CA_ParametersNRDC_v1700;
struct MRDC_Parameters_v1700;
struct BandParameters_v1710;

/* BandCombination-v1700 */
typedef struct BandCombination_v1700 {
	struct CA_ParametersNR_v1700	*ca_ParametersNR_v1700;	/* OPTIONAL */
	struct CA_ParametersNRDC_v1700	*ca_ParametersNRDC_v1700;	/* OPTIONAL */
	struct MRDC_Parameters_v1700	*mrdc_Parameters_v1700;	/* OPTIONAL */
	struct BandCombination_v1700__bandList_v1710 {
		A_SEQUENCE_OF(struct BandParameters_v1710) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *bandList_v1710;
	BIT_STRING_t	*supportedBandCombListPerBC_SL_RelayDiscovery_r17;	/* OPTIONAL */
	BIT_STRING_t	*supportedBandCombListPerBC_SL_NonRelayDiscovery_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BandCombination_v1700_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BandCombination_v1700;
extern asn_SEQUENCE_specifics_t asn_SPC_BandCombination_v1700_specs_1;
extern asn_TYPE_member_t asn_MBR_BandCombination_v1700_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CA-ParametersNR-v1700.h"
#include "CA-ParametersNRDC-v1700.h"
#include "MRDC-Parameters-v1700.h"
#include "BandParameters-v1710.h"

#endif	/* _BandCombination_v1700_H_ */
#include <asn_internal.h>
