/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_BWP_DownlinkDedicated_H_
#define	_BWP_DownlinkDedicated_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>
#include <BIT_STRING.h>
#include <BOOLEAN.h>
#include "MeasObjectId.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SetupRelease_PDCCH_Config;
struct SetupRelease_PDSCH_Config;
struct SetupRelease_SPS_Config;
struct SetupRelease_RadioLinkMonitoringConfig;
struct SPS_ConfigToAddModList_r16;
struct SPS_ConfigToReleaseList_r16;
struct SPS_ConfigDeactivationStateList_r16;
struct SetupRelease_BeamFailureRecoveryRSConfig_r16;
struct SetupRelease_CFR_ConfigMulticast_r17;
struct DL_PPW_PreConfigToAddModList_r17;
struct DL_PPW_PreConfigToReleaseList_r17;
struct NonCellDefiningSSB_r17;

/* BWP-DownlinkDedicated */
typedef struct BWP_DownlinkDedicated {
	struct SetupRelease_PDCCH_Config	*pdcch_Config;	/* OPTIONAL */
	struct SetupRelease_PDSCH_Config	*pdsch_Config;	/* OPTIONAL */
	struct SetupRelease_SPS_Config	*sps_Config;	/* OPTIONAL */
	struct SetupRelease_RadioLinkMonitoringConfig	*radioLinkMonitoringConfig;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct BWP_DownlinkDedicated__ext1 {
		struct SPS_ConfigToAddModList_r16	*sps_ConfigToAddModList_r16;	/* OPTIONAL */
		struct SPS_ConfigToReleaseList_r16	*sps_ConfigToReleaseList_r16;	/* OPTIONAL */
		struct SPS_ConfigDeactivationStateList_r16	*sps_ConfigDeactivationStateList_r16;	/* OPTIONAL */
		struct SetupRelease_BeamFailureRecoveryRSConfig_r16	*beamFailureRecoverySCellConfig_r16;	/* OPTIONAL */
		struct SetupRelease_PDCCH_Config	*sl_PDCCH_Config_r16;	/* OPTIONAL */
		struct SetupRelease_PDCCH_Config	*sl_V2X_PDCCH_Config_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct BWP_DownlinkDedicated__ext2 {
		BIT_STRING_t	*preConfGapStatus_r17;	/* OPTIONAL */
		struct SetupRelease_BeamFailureRecoveryRSConfig_r16	*beamFailureRecoverySpCellConfig_r17;	/* OPTIONAL */
		BOOLEAN_t	*harq_FeedbackEnablingforSPSactive_r17;	/* OPTIONAL */
		struct SetupRelease_CFR_ConfigMulticast_r17	*cfr_ConfigMulticast_r17;	/* OPTIONAL */
		struct DL_PPW_PreConfigToAddModList_r17	*dl_PPW_PreConfigToAddModList_r17;	/* OPTIONAL */
		struct DL_PPW_PreConfigToReleaseList_r17	*dl_PPW_PreConfigToReleaseList_r17;	/* OPTIONAL */
		struct NonCellDefiningSSB_r17	*nonCellDefiningSSB_r17;	/* OPTIONAL */
		MeasObjectId_t	*servingCellMO_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BWP_DownlinkDedicated_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BWP_DownlinkDedicated;
extern asn_SEQUENCE_specifics_t asn_SPC_BWP_DownlinkDedicated_specs_1;
extern asn_TYPE_member_t asn_MBR_BWP_DownlinkDedicated_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SetupRelease.h"
#include "SPS-ConfigToAddModList-r16.h"
#include "SPS-ConfigToReleaseList-r16.h"
#include "SPS-ConfigDeactivationStateList-r16.h"
#include "DL-PPW-PreConfigToAddModList-r17.h"
#include "DL-PPW-PreConfigToReleaseList-r17.h"
#include "NonCellDefiningSSB-r17.h"

#endif	/* _BWP_DownlinkDedicated_H_ */
#include <asn_internal.h>
