/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_CA_ParametersNR_v1640_H_
#define	_CA_ParametersNR_v1640_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <NativeInteger.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16 {
	CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16_supported	= 0
} e_CA_ParametersNR_v1640__uplinkTxDC_TwoCarrierReport_r16;
typedef enum CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16 {
	CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16_supported	= 0
} e_CA_ParametersNR_v1640__diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16;
typedef enum CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16 {
	CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16_supported	= 0
} e_CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16;
typedef enum CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16 {
	CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16_supported	= 0
} e_CA_ParametersNR_v1640__diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16;

/* Forward declarations */
struct PUCCH_Grp_CarrierTypes_r16;
struct TwoPUCCH_Grp_Configurations_r16;

/* CA-ParametersNR-v1640 */
typedef struct CA_ParametersNR_v1640 {
	long	*uplinkTxDC_TwoCarrierReport_r16;	/* OPTIONAL */
	struct PUCCH_Grp_CarrierTypes_r16	*maxUpTo3Diff_NumerologiesConfigSinglePUCCH_grp_r16;	/* OPTIONAL */
	struct PUCCH_Grp_CarrierTypes_r16	*maxUpTo4Diff_NumerologiesConfigSinglePUCCH_grp_r16;	/* OPTIONAL */
	struct CA_ParametersNR_v1640__twoPUCCH_Grp_ConfigurationsList_r16 {
		A_SEQUENCE_OF(struct TwoPUCCH_Grp_Configurations_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *twoPUCCH_Grp_ConfigurationsList_r16;
	long	*diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16;	/* OPTIONAL */
	long	*diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16;	/* OPTIONAL */
	long	*diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16;	/* OPTIONAL */
	long	*pdcch_MonitoringCA_NonAlignedSpan_r16;	/* OPTIONAL */
	struct CA_ParametersNR_v1640__pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16 {
		long	 pdcch_BlindDetectionCA1_r16;
		long	 pdcch_BlindDetectionCA2_r16;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *pdcch_BlindDetectionCA_Mixed_NonAlignedSpan_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CA_ParametersNR_v1640_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_uplinkTxDC_TwoCarrierReport_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_diffNumerologyAcrossPUCCH_Group_CarrierTypes_r16_8;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_diffNumerologyWithinPUCCH_GroupSmallerSCS_CarrierTypes_r16_10;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_diffNumerologyWithinPUCCH_GroupLargerSCS_CarrierTypes_r16_12;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CA_ParametersNR_v1640;
extern asn_SEQUENCE_specifics_t asn_SPC_CA_ParametersNR_v1640_specs_1;
extern asn_TYPE_member_t asn_MBR_CA_ParametersNR_v1640_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PUCCH-Grp-CarrierTypes-r16.h"
#include "TwoPUCCH-Grp-Configurations-r16.h"

#endif	/* _CA_ParametersNR_v1640_H_ */
#include <asn_internal.h>
