/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_CellGrouping_r16_H_
#define	_CellGrouping_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "FreqBandIndicatorNR.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CellGrouping_r16__mode_r16 {
	CellGrouping_r16__mode_r16_sync	= 0,
	CellGrouping_r16__mode_r16_async	= 1
} e_CellGrouping_r16__mode_r16;

/* CellGrouping-r16 */
typedef struct CellGrouping_r16 {
	struct CellGrouping_r16__mcg_r16 {
		A_SEQUENCE_OF(FreqBandIndicatorNR_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} mcg_r16;
	struct CellGrouping_r16__scg_r16 {
		A_SEQUENCE_OF(FreqBandIndicatorNR_t) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} scg_r16;
	long	 mode_r16;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellGrouping_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_mode_r16_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CellGrouping_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_CellGrouping_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_CellGrouping_r16_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _CellGrouping_r16_H_ */
#include <asn_internal.h>
