/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_CG_SDT_Configuration_r17_H_
#define	_CG_SDT_Configuration_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <BIT_STRING.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CG_SDT_Configuration_r17__sdt_SSB_Subset_r17_PR {
	CG_SDT_Configuration_r17__sdt_SSB_Subset_r17_PR_NOTHING,	/* No components present */
	CG_SDT_Configuration_r17__sdt_SSB_Subset_r17_PR_shortBitmap_r17,
	CG_SDT_Configuration_r17__sdt_SSB_Subset_r17_PR_mediumBitmap_r17,
	CG_SDT_Configuration_r17__sdt_SSB_Subset_r17_PR_longBitmap_r17
} CG_SDT_Configuration_r17__sdt_SSB_Subset_r17_PR;
typedef enum CG_SDT_Configuration_r17__sdt_SSB_PerCG_PUSCH_r17 {
	CG_SDT_Configuration_r17__sdt_SSB_PerCG_PUSCH_r17_oneEighth	= 0,
	CG_SDT_Configuration_r17__sdt_SSB_PerCG_PUSCH_r17_oneFourth	= 1,
	CG_SDT_Configuration_r17__sdt_SSB_PerCG_PUSCH_r17_half	= 2,
	CG_SDT_Configuration_r17__sdt_SSB_PerCG_PUSCH_r17_one	= 3,
	CG_SDT_Configuration_r17__sdt_SSB_PerCG_PUSCH_r17_two	= 4,
	CG_SDT_Configuration_r17__sdt_SSB_PerCG_PUSCH_r17_four	= 5,
	CG_SDT_Configuration_r17__sdt_SSB_PerCG_PUSCH_r17_eight	= 6,
	CG_SDT_Configuration_r17__sdt_SSB_PerCG_PUSCH_r17_sixteen	= 7
} e_CG_SDT_Configuration_r17__sdt_SSB_PerCG_PUSCH_r17;
typedef enum CG_SDT_Configuration_r17__sdt_Alpha_r17 {
	CG_SDT_Configuration_r17__sdt_Alpha_r17_alpha0	= 0,
	CG_SDT_Configuration_r17__sdt_Alpha_r17_alpha04	= 1,
	CG_SDT_Configuration_r17__sdt_Alpha_r17_alpha05	= 2,
	CG_SDT_Configuration_r17__sdt_Alpha_r17_alpha06	= 3,
	CG_SDT_Configuration_r17__sdt_Alpha_r17_alpha07	= 4,
	CG_SDT_Configuration_r17__sdt_Alpha_r17_alpha08	= 5,
	CG_SDT_Configuration_r17__sdt_Alpha_r17_alpha09	= 6,
	CG_SDT_Configuration_r17__sdt_Alpha_r17_alpha1	= 7
} e_CG_SDT_Configuration_r17__sdt_Alpha_r17;
typedef enum CG_SDT_Configuration_r17__sdt_DMRS_Ports_r17_PR {
	CG_SDT_Configuration_r17__sdt_DMRS_Ports_r17_PR_NOTHING,	/* No components present */
	CG_SDT_Configuration_r17__sdt_DMRS_Ports_r17_PR_dmrsType1_r17,
	CG_SDT_Configuration_r17__sdt_DMRS_Ports_r17_PR_dmrsType2_r17
} CG_SDT_Configuration_r17__sdt_DMRS_Ports_r17_PR;

/* CG-SDT-Configuration-r17 */
typedef struct CG_SDT_Configuration_r17 {
	long	*cg_SDT_RetransmissionTimer;	/* OPTIONAL */
	struct CG_SDT_Configuration_r17__sdt_SSB_Subset_r17 {
		CG_SDT_Configuration_r17__sdt_SSB_Subset_r17_PR present;
		union CG_SDT_Configuration_r17__sdt_SSB_Subset_r17_u {
			BIT_STRING_t	 shortBitmap_r17;
			BIT_STRING_t	 mediumBitmap_r17;
			BIT_STRING_t	 longBitmap_r17;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sdt_SSB_Subset_r17;
	long	*sdt_SSB_PerCG_PUSCH_r17;	/* OPTIONAL */
	long	*sdt_P0_PUSCH_r17;	/* OPTIONAL */
	long	*sdt_Alpha_r17;	/* OPTIONAL */
	struct CG_SDT_Configuration_r17__sdt_DMRS_Ports_r17 {
		CG_SDT_Configuration_r17__sdt_DMRS_Ports_r17_PR present;
		union CG_SDT_Configuration_r17__sdt_DMRS_Ports_r17_u {
			BIT_STRING_t	 dmrsType1_r17;
			BIT_STRING_t	 dmrsType2_r17;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sdt_DMRS_Ports_r17;
	long	*sdt_NrofDMRS_Sequences_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CG_SDT_Configuration_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_sdt_SSB_PerCG_PUSCH_r17_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_sdt_Alpha_r17_17;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CG_SDT_Configuration_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_CG_SDT_Configuration_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_CG_SDT_Configuration_r17_1[7];

#ifdef __cplusplus
}
#endif

#endif	/* _CG_SDT_Configuration_r17_H_ */
#include <asn_internal.h>
