/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_CMRGroupingAndPairing_r17_H_
#define	_CMRGroupingAndPairing_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NZP_CSI_RS_Pairing_r17;

/* CMRGroupingAndPairing-r17 */
typedef struct CMRGroupingAndPairing_r17 {
	long	 nrofResourcesGroup1_r17;
	struct NZP_CSI_RS_Pairing_r17	*pair1OfNZP_CSI_RS_r17;	/* OPTIONAL */
	struct NZP_CSI_RS_Pairing_r17	*pair2OfNZP_CSI_RS_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CMRGroupingAndPairing_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CMRGroupingAndPairing_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_CMRGroupingAndPairing_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_CMRGroupingAndPairing_r17_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "NZP-CSI-RS-Pairing-r17.h"

#endif	/* _CMRGroupingAndPairing_r17_H_ */
#include <asn_internal.h>
