/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_DedicatedSIBRequest_r16_H_
#define	_DedicatedSIBRequest_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DedicatedSIBRequest_r16__criticalExtensions_PR {
	DedicatedSIBRequest_r16__criticalExtensions_PR_NOTHING,	/* No components present */
	DedicatedSIBRequest_r16__criticalExtensions_PR_dedicatedSIBRequest_r16,
	DedicatedSIBRequest_r16__criticalExtensions_PR_criticalExtensionsFuture
} DedicatedSIBRequest_r16__criticalExtensions_PR;

/* Forward declarations */
struct DedicatedSIBRequest_r16_IEs;

/* DedicatedSIBRequest-r16 */
typedef struct DedicatedSIBRequest_r16 {
	struct DedicatedSIBRequest_r16__criticalExtensions {
		DedicatedSIBRequest_r16__criticalExtensions_PR present;
		union DedicatedSIBRequest_r16__criticalExtensions_u {
			struct DedicatedSIBRequest_r16_IEs	*dedicatedSIBRequest_r16;
			struct DedicatedSIBRequest_r16__criticalExtensions__criticalExtensionsFuture {
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *criticalExtensionsFuture;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} criticalExtensions;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DedicatedSIBRequest_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DedicatedSIBRequest_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_DedicatedSIBRequest_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_DedicatedSIBRequest_r16_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "DedicatedSIBRequest-r16-IEs.h"

#endif	/* _DedicatedSIBRequest_r16_H_ */
#include <asn_internal.h>
