/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_FeatureSetDownlinkPerCC_v1720_H_
#define	_FeatureSetDownlinkPerCC_v1720_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FeatureSetDownlinkPerCC_v1720__maxModulationOrderForMulticastDataRateCalculation_r17 {
	FeatureSetDownlinkPerCC_v1720__maxModulationOrderForMulticastDataRateCalculation_r17_qam64	= 0,
	FeatureSetDownlinkPerCC_v1720__maxModulationOrderForMulticastDataRateCalculation_r17_qam256	= 1,
	FeatureSetDownlinkPerCC_v1720__maxModulationOrderForMulticastDataRateCalculation_r17_qam1024	= 2
} e_FeatureSetDownlinkPerCC_v1720__maxModulationOrderForMulticastDataRateCalculation_r17;
typedef enum FeatureSetDownlinkPerCC_v1720__fdm_BroadcastUnicast_r17 {
	FeatureSetDownlinkPerCC_v1720__fdm_BroadcastUnicast_r17_supported	= 0
} e_FeatureSetDownlinkPerCC_v1720__fdm_BroadcastUnicast_r17;
typedef enum FeatureSetDownlinkPerCC_v1720__fdm_MulticastUnicast_r17 {
	FeatureSetDownlinkPerCC_v1720__fdm_MulticastUnicast_r17_supported	= 0
} e_FeatureSetDownlinkPerCC_v1720__fdm_MulticastUnicast_r17;

/* FeatureSetDownlinkPerCC-v1720 */
typedef struct FeatureSetDownlinkPerCC_v1720 {
	long	*maxModulationOrderForMulticastDataRateCalculation_r17;	/* OPTIONAL */
	long	*fdm_BroadcastUnicast_r17;	/* OPTIONAL */
	long	*fdm_MulticastUnicast_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} FeatureSetDownlinkPerCC_v1720_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_maxModulationOrderForMulticastDataRateCalculation_r17_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_fdm_BroadcastUnicast_r17_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_fdm_MulticastUnicast_r17_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_FeatureSetDownlinkPerCC_v1720;
extern asn_SEQUENCE_specifics_t asn_SPC_FeatureSetDownlinkPerCC_v1720_specs_1;
extern asn_TYPE_member_t asn_MBR_FeatureSetDownlinkPerCC_v1720_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _FeatureSetDownlinkPerCC_v1720_H_ */
#include <asn_internal.h>
