/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_MBS_RNTI_SpecificConfig_r17_H_
#define	_MBS_RNTI_SpecificConfig_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MBS-RNTI-SpecificConfigId-r17.h"
#include <NativeEnumerated.h>
#include "RNTI-Value.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MBS_RNTI_SpecificConfig_r17__groupCommon_RNTI_r17_PR {
	MBS_RNTI_SpecificConfig_r17__groupCommon_RNTI_r17_PR_NOTHING,	/* No components present */
	MBS_RNTI_SpecificConfig_r17__groupCommon_RNTI_r17_PR_g_RNTI,
	MBS_RNTI_SpecificConfig_r17__groupCommon_RNTI_r17_PR_g_CS_RNTI
} MBS_RNTI_SpecificConfig_r17__groupCommon_RNTI_r17_PR;
typedef enum MBS_RNTI_SpecificConfig_r17__harq_FeedbackEnablerMulticast_r17 {
	MBS_RNTI_SpecificConfig_r17__harq_FeedbackEnablerMulticast_r17_dci_enabler	= 0,
	MBS_RNTI_SpecificConfig_r17__harq_FeedbackEnablerMulticast_r17_enabled	= 1
} e_MBS_RNTI_SpecificConfig_r17__harq_FeedbackEnablerMulticast_r17;
typedef enum MBS_RNTI_SpecificConfig_r17__harq_FeedbackOptionMulticast_r17 {
	MBS_RNTI_SpecificConfig_r17__harq_FeedbackOptionMulticast_r17_ack_nack	= 0,
	MBS_RNTI_SpecificConfig_r17__harq_FeedbackOptionMulticast_r17_nack_only	= 1
} e_MBS_RNTI_SpecificConfig_r17__harq_FeedbackOptionMulticast_r17;
typedef enum MBS_RNTI_SpecificConfig_r17__pdsch_AggregationFactor_r17 {
	MBS_RNTI_SpecificConfig_r17__pdsch_AggregationFactor_r17_n2	= 0,
	MBS_RNTI_SpecificConfig_r17__pdsch_AggregationFactor_r17_n4	= 1,
	MBS_RNTI_SpecificConfig_r17__pdsch_AggregationFactor_r17_n8	= 2
} e_MBS_RNTI_SpecificConfig_r17__pdsch_AggregationFactor_r17;

/* Forward declarations */
struct SetupRelease_DRX_ConfigPTM_r17;

/* MBS-RNTI-SpecificConfig-r17 */
typedef struct MBS_RNTI_SpecificConfig_r17 {
	MBS_RNTI_SpecificConfigId_r17_t	 mbs_RNTI_SpecificConfigId_r17;
	struct MBS_RNTI_SpecificConfig_r17__groupCommon_RNTI_r17 {
		MBS_RNTI_SpecificConfig_r17__groupCommon_RNTI_r17_PR present;
		union MBS_RNTI_SpecificConfig_r17__groupCommon_RNTI_r17_u {
			RNTI_Value_t	 g_RNTI;
			RNTI_Value_t	 g_CS_RNTI;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} groupCommon_RNTI_r17;
	struct SetupRelease_DRX_ConfigPTM_r17	*drx_ConfigPTM_r17;	/* OPTIONAL */
	long	*harq_FeedbackEnablerMulticast_r17;	/* OPTIONAL */
	long	*harq_FeedbackOptionMulticast_r17;	/* OPTIONAL */
	long	*pdsch_AggregationFactor_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MBS_RNTI_SpecificConfig_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_harq_FeedbackEnablerMulticast_r17_7;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_harq_FeedbackOptionMulticast_r17_10;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_pdsch_AggregationFactor_r17_13;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MBS_RNTI_SpecificConfig_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_MBS_RNTI_SpecificConfig_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_MBS_RNTI_SpecificConfig_r17_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SetupRelease.h"

#endif	/* _MBS_RNTI_SpecificConfig_r17_H_ */
#include <asn_internal.h>
