/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_MeasResultIdleEUTRA_r16_H_
#define	_MeasResultIdleEUTRA_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct MeasResultsPerCarrierIdleEUTRA_r16;

/* MeasResultIdleEUTRA-r16 */
typedef struct MeasResultIdleEUTRA_r16 {
	struct MeasResultIdleEUTRA_r16__measResultsPerCarrierListIdleEUTRA_r16 {
		A_SEQUENCE_OF(struct MeasResultsPerCarrierIdleEUTRA_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} measResultsPerCarrierListIdleEUTRA_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasResultIdleEUTRA_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasResultIdleEUTRA_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasResultIdleEUTRA_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasResultIdleEUTRA_r16_1[1];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "MeasResultsPerCarrierIdleEUTRA-r16.h"

#endif	/* _MeasResultIdleEUTRA_r16_H_ */
#include <asn_internal.h>
