/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_MeasAndMobParametersFRX_Diff_H_
#define	_MeasAndMobParametersFRX_Diff_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasAndMobParametersFRX_Diff__ss_SINR_Meas {
	MeasAndMobParametersFRX_Diff__ss_SINR_Meas_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ss_SINR_Meas;
typedef enum MeasAndMobParametersFRX_Diff__csi_RSRP_AndRSRQ_MeasWithSSB {
	MeasAndMobParametersFRX_Diff__csi_RSRP_AndRSRQ_MeasWithSSB_supported	= 0
} e_MeasAndMobParametersFRX_Diff__csi_RSRP_AndRSRQ_MeasWithSSB;
typedef enum MeasAndMobParametersFRX_Diff__csi_RSRP_AndRSRQ_MeasWithoutSSB {
	MeasAndMobParametersFRX_Diff__csi_RSRP_AndRSRQ_MeasWithoutSSB_supported	= 0
} e_MeasAndMobParametersFRX_Diff__csi_RSRP_AndRSRQ_MeasWithoutSSB;
typedef enum MeasAndMobParametersFRX_Diff__csi_SINR_Meas {
	MeasAndMobParametersFRX_Diff__csi_SINR_Meas_supported	= 0
} e_MeasAndMobParametersFRX_Diff__csi_SINR_Meas;
typedef enum MeasAndMobParametersFRX_Diff__csi_RS_RLM {
	MeasAndMobParametersFRX_Diff__csi_RS_RLM_supported	= 0
} e_MeasAndMobParametersFRX_Diff__csi_RS_RLM;
typedef enum MeasAndMobParametersFRX_Diff__ext1__handoverInterF {
	MeasAndMobParametersFRX_Diff__ext1__handoverInterF_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext1__handoverInterF;
typedef enum MeasAndMobParametersFRX_Diff__ext1__handoverLTE_EPC {
	MeasAndMobParametersFRX_Diff__ext1__handoverLTE_EPC_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext1__handoverLTE_EPC;
typedef enum MeasAndMobParametersFRX_Diff__ext1__handoverLTE_5GC {
	MeasAndMobParametersFRX_Diff__ext1__handoverLTE_5GC_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext1__handoverLTE_5GC;
typedef enum MeasAndMobParametersFRX_Diff__ext2__maxNumberResource_CSI_RS_RLM {
	MeasAndMobParametersFRX_Diff__ext2__maxNumberResource_CSI_RS_RLM_n2	= 0,
	MeasAndMobParametersFRX_Diff__ext2__maxNumberResource_CSI_RS_RLM_n4	= 1,
	MeasAndMobParametersFRX_Diff__ext2__maxNumberResource_CSI_RS_RLM_n6	= 2,
	MeasAndMobParametersFRX_Diff__ext2__maxNumberResource_CSI_RS_RLM_n8	= 3
} e_MeasAndMobParametersFRX_Diff__ext2__maxNumberResource_CSI_RS_RLM;
typedef enum MeasAndMobParametersFRX_Diff__ext3__simultaneousRxDataSSB_DiffNumerology {
	MeasAndMobParametersFRX_Diff__ext3__simultaneousRxDataSSB_DiffNumerology_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext3__simultaneousRxDataSSB_DiffNumerology;
typedef enum MeasAndMobParametersFRX_Diff__ext4__nr_AutonomousGaps_r16 {
	MeasAndMobParametersFRX_Diff__ext4__nr_AutonomousGaps_r16_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext4__nr_AutonomousGaps_r16;
typedef enum MeasAndMobParametersFRX_Diff__ext4__nr_AutonomousGaps_ENDC_r16 {
	MeasAndMobParametersFRX_Diff__ext4__nr_AutonomousGaps_ENDC_r16_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext4__nr_AutonomousGaps_ENDC_r16;
typedef enum MeasAndMobParametersFRX_Diff__ext4__nr_AutonomousGaps_NEDC_r16 {
	MeasAndMobParametersFRX_Diff__ext4__nr_AutonomousGaps_NEDC_r16_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext4__nr_AutonomousGaps_NEDC_r16;
typedef enum MeasAndMobParametersFRX_Diff__ext4__nr_AutonomousGaps_NRDC_r16 {
	MeasAndMobParametersFRX_Diff__ext4__nr_AutonomousGaps_NRDC_r16_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext4__nr_AutonomousGaps_NRDC_r16;
typedef enum MeasAndMobParametersFRX_Diff__ext4__dummy {
	MeasAndMobParametersFRX_Diff__ext4__dummy_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext4__dummy;
typedef enum MeasAndMobParametersFRX_Diff__ext4__cli_RSSI_Meas_r16 {
	MeasAndMobParametersFRX_Diff__ext4__cli_RSSI_Meas_r16_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext4__cli_RSSI_Meas_r16;
typedef enum MeasAndMobParametersFRX_Diff__ext4__cli_SRS_RSRP_Meas_r16 {
	MeasAndMobParametersFRX_Diff__ext4__cli_SRS_RSRP_Meas_r16_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext4__cli_SRS_RSRP_Meas_r16;
typedef enum MeasAndMobParametersFRX_Diff__ext4__interFrequencyMeas_NoGap_r16 {
	MeasAndMobParametersFRX_Diff__ext4__interFrequencyMeas_NoGap_r16_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext4__interFrequencyMeas_NoGap_r16;
typedef enum MeasAndMobParametersFRX_Diff__ext4__simultaneousRxDataSSB_DiffNumerology_Inter_r16 {
	MeasAndMobParametersFRX_Diff__ext4__simultaneousRxDataSSB_DiffNumerology_Inter_r16_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext4__simultaneousRxDataSSB_DiffNumerology_Inter_r16;
typedef enum MeasAndMobParametersFRX_Diff__ext4__idleInactiveNR_MeasReport_r16 {
	MeasAndMobParametersFRX_Diff__ext4__idleInactiveNR_MeasReport_r16_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext4__idleInactiveNR_MeasReport_r16;
typedef enum MeasAndMobParametersFRX_Diff__ext4__idleInactiveNR_MeasBeamReport_r16 {
	MeasAndMobParametersFRX_Diff__ext4__idleInactiveNR_MeasBeamReport_r16_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext4__idleInactiveNR_MeasBeamReport_r16;
typedef enum MeasAndMobParametersFRX_Diff__ext5__increasedNumberofCSIRSPerMO_r16 {
	MeasAndMobParametersFRX_Diff__ext5__increasedNumberofCSIRSPerMO_r16_supported	= 0
} e_MeasAndMobParametersFRX_Diff__ext5__increasedNumberofCSIRSPerMO_r16;

/* MeasAndMobParametersFRX-Diff */
typedef struct MeasAndMobParametersFRX_Diff {
	long	*ss_SINR_Meas;	/* OPTIONAL */
	long	*csi_RSRP_AndRSRQ_MeasWithSSB;	/* OPTIONAL */
	long	*csi_RSRP_AndRSRQ_MeasWithoutSSB;	/* OPTIONAL */
	long	*csi_SINR_Meas;	/* OPTIONAL */
	long	*csi_RS_RLM;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct MeasAndMobParametersFRX_Diff__ext1 {
		long	*handoverInterF;	/* OPTIONAL */
		long	*handoverLTE_EPC;	/* OPTIONAL */
		long	*handoverLTE_5GC;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct MeasAndMobParametersFRX_Diff__ext2 {
		long	*maxNumberResource_CSI_RS_RLM;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	struct MeasAndMobParametersFRX_Diff__ext3 {
		long	*simultaneousRxDataSSB_DiffNumerology;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext3;
	struct MeasAndMobParametersFRX_Diff__ext4 {
		long	*nr_AutonomousGaps_r16;	/* OPTIONAL */
		long	*nr_AutonomousGaps_ENDC_r16;	/* OPTIONAL */
		long	*nr_AutonomousGaps_NEDC_r16;	/* OPTIONAL */
		long	*nr_AutonomousGaps_NRDC_r16;	/* OPTIONAL */
		long	*dummy;	/* OPTIONAL */
		long	*cli_RSSI_Meas_r16;	/* OPTIONAL */
		long	*cli_SRS_RSRP_Meas_r16;	/* OPTIONAL */
		long	*interFrequencyMeas_NoGap_r16;	/* OPTIONAL */
		long	*simultaneousRxDataSSB_DiffNumerology_Inter_r16;	/* OPTIONAL */
		long	*idleInactiveNR_MeasReport_r16;	/* OPTIONAL */
		long	*idleInactiveNR_MeasBeamReport_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext4;
	struct MeasAndMobParametersFRX_Diff__ext5 {
		long	*increasedNumberofCSIRSPerMO_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext5;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasAndMobParametersFRX_Diff_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_ss_SINR_Meas_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_csi_RSRP_AndRSRQ_MeasWithSSB_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_csi_RSRP_AndRSRQ_MeasWithoutSSB_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_csi_SINR_Meas_8;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_csi_RS_RLM_10;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_handoverInterF_14;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_handoverLTE_EPC_16;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_handoverLTE_5GC_18;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_maxNumberResource_CSI_RS_RLM_21;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_simultaneousRxDataSSB_DiffNumerology_27;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_nr_AutonomousGaps_r16_30;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_nr_AutonomousGaps_ENDC_r16_32;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_nr_AutonomousGaps_NEDC_r16_34;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_nr_AutonomousGaps_NRDC_r16_36;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_dummy_38;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_cli_RSSI_Meas_r16_40;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_cli_SRS_RSRP_Meas_r16_42;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_interFrequencyMeas_NoGap_r16_44;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_simultaneousRxDataSSB_DiffNumerology_Inter_r16_46;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_idleInactiveNR_MeasReport_r16_48;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_idleInactiveNR_MeasBeamReport_r16_50;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_increasedNumberofCSIRSPerMO_r16_53;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MeasAndMobParametersFRX_Diff;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasAndMobParametersFRX_Diff_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasAndMobParametersFRX_Diff_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasAndMobParametersFRX_Diff_H_ */
#include <asn_internal.h>
