/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_MeasObjectEUTRA_H_
#define	_MeasObjectEUTRA_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ARFCN-ValueEUTRA.h"
#include "EUTRA-AllowedMeasBandwidth.h"
#include "EUTRA-PresenceAntennaPort1.h"
#include "EUTRA-Q-OffsetRange.h"
#include <BOOLEAN.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "MeasGapId-r17.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EUTRA_CellIndexList;
struct EUTRA_Cell;
struct EUTRA_ExcludedCell;

/* MeasObjectEUTRA */
typedef struct MeasObjectEUTRA {
	ARFCN_ValueEUTRA_t	 carrierFreq;
	EUTRA_AllowedMeasBandwidth_t	 allowedMeasBandwidth;
	struct EUTRA_CellIndexList	*cellsToRemoveListEUTRAN;	/* OPTIONAL */
	struct MeasObjectEUTRA__cellsToAddModListEUTRAN {
		A_SEQUENCE_OF(struct EUTRA_Cell) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *cellsToAddModListEUTRAN;
	struct EUTRA_CellIndexList	*excludedCellsToRemoveListEUTRAN;	/* OPTIONAL */
	struct MeasObjectEUTRA__excludedCellsToAddModListEUTRAN {
		A_SEQUENCE_OF(struct EUTRA_ExcludedCell) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *excludedCellsToAddModListEUTRAN;
	EUTRA_PresenceAntennaPort1_t	 eutra_PresenceAntennaPort1;
	EUTRA_Q_OffsetRange_t	*eutra_Q_OffsetRange;	/* OPTIONAL */
	BOOLEAN_t	 widebandRSRQ_Meas;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct MeasObjectEUTRA__ext1 {
		MeasGapId_r17_t	*associatedMeasGap_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasObjectEUTRA_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MeasObjectEUTRA;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasObjectEUTRA_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasObjectEUTRA_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "EUTRA-CellIndexList.h"
#include "EUTRA-Cell.h"
#include "EUTRA-ExcludedCell.h"

#endif	/* _MeasObjectEUTRA_H_ */
#include <asn_internal.h>
