/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_MeasAndMobParametersFR2_2_r17_H_
#define	_MeasAndMobParametersFR2_2_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasAndMobParametersFR2_2_r17__handoverInterF_r17 {
	MeasAndMobParametersFR2_2_r17__handoverInterF_r17_supported	= 0
} e_MeasAndMobParametersFR2_2_r17__handoverInterF_r17;
typedef enum MeasAndMobParametersFR2_2_r17__handoverLTE_EPC_r17 {
	MeasAndMobParametersFR2_2_r17__handoverLTE_EPC_r17_supported	= 0
} e_MeasAndMobParametersFR2_2_r17__handoverLTE_EPC_r17;
typedef enum MeasAndMobParametersFR2_2_r17__handoverLTE_5GC_r17 {
	MeasAndMobParametersFR2_2_r17__handoverLTE_5GC_r17_supported	= 0
} e_MeasAndMobParametersFR2_2_r17__handoverLTE_5GC_r17;
typedef enum MeasAndMobParametersFR2_2_r17__idleInactiveNR_MeasReport_r17 {
	MeasAndMobParametersFR2_2_r17__idleInactiveNR_MeasReport_r17_supported	= 0
} e_MeasAndMobParametersFR2_2_r17__idleInactiveNR_MeasReport_r17;

/* MeasAndMobParametersFR2-2-r17 */
typedef struct MeasAndMobParametersFR2_2_r17 {
	long	*handoverInterF_r17;	/* OPTIONAL */
	long	*handoverLTE_EPC_r17;	/* OPTIONAL */
	long	*handoverLTE_5GC_r17;	/* OPTIONAL */
	long	*idleInactiveNR_MeasReport_r17;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasAndMobParametersFR2_2_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_handoverInterF_r17_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_handoverLTE_EPC_r17_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_handoverLTE_5GC_r17_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_idleInactiveNR_MeasReport_r17_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MeasAndMobParametersFR2_2_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasAndMobParametersFR2_2_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasAndMobParametersFR2_2_r17_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _MeasAndMobParametersFR2_2_r17_H_ */
#include <asn_internal.h>
