/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_MeasReportAppLayer_r17_H_
#define	_MeasReportAppLayer_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MeasConfigAppLayerId-r17.h"
#include <OCTET_STRING.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MeasReportAppLayer_r17__appLayerSessionStatus_r17 {
	MeasReportAppLayer_r17__appLayerSessionStatus_r17_started	= 0,
	MeasReportAppLayer_r17__appLayerSessionStatus_r17_stopped	= 1
} e_MeasReportAppLayer_r17__appLayerSessionStatus_r17;

/* Forward declarations */
struct RAN_VisibleMeasurements_r17;

/* MeasReportAppLayer-r17 */
typedef struct MeasReportAppLayer_r17 {
	MeasConfigAppLayerId_r17_t	 measConfigAppLayerId_r17;
	OCTET_STRING_t	*measReportAppLayerContainer_r17;	/* OPTIONAL */
	long	*appLayerSessionStatus_r17;	/* OPTIONAL */
	struct RAN_VisibleMeasurements_r17	*ran_VisibleMeasurements_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MeasReportAppLayer_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_appLayerSessionStatus_r17_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_MeasReportAppLayer_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_MeasReportAppLayer_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_MeasReportAppLayer_r17_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RAN-VisibleMeasurements-r17.h"

#endif	/* _MeasReportAppLayer_r17_H_ */
#include <asn_internal.h>
