/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_MPE_Resource_r17_H_
#define	_MPE_Resource_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MPE-ResourceId-r17.h"
#include "ServCellIndex.h"
#include "AdditionalPCIIndex-r17.h"
#include "NZP-CSI-RS-ResourceId.h"
#include "SSB-Index.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum MPE_Resource_r17__mpe_ReferenceSignal_r17_PR {
	MPE_Resource_r17__mpe_ReferenceSignal_r17_PR_NOTHING,	/* No components present */
	MPE_Resource_r17__mpe_ReferenceSignal_r17_PR_csi_RS_Resource_r17,
	MPE_Resource_r17__mpe_ReferenceSignal_r17_PR_ssb_Resource_r17
} MPE_Resource_r17__mpe_ReferenceSignal_r17_PR;

/* MPE-Resource-r17 */
typedef struct MPE_Resource_r17 {
	MPE_ResourceId_r17_t	 mpe_ResourceId_r17;
	ServCellIndex_t	*cell_r17;	/* OPTIONAL */
	AdditionalPCIIndex_r17_t	*additionalPCI_r17;	/* OPTIONAL */
	struct MPE_Resource_r17__mpe_ReferenceSignal_r17 {
		MPE_Resource_r17__mpe_ReferenceSignal_r17_PR present;
		union MPE_Resource_r17__mpe_ReferenceSignal_r17_u {
			NZP_CSI_RS_ResourceId_t	 csi_RS_Resource_r17;
			SSB_Index_t	 ssb_Resource_r17;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} mpe_ReferenceSignal_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MPE_Resource_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MPE_Resource_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_MPE_Resource_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_MPE_Resource_r17_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _MPE_Resource_r17_H_ */
#include <asn_internal.h>
