/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_OverheatingAssistance_r17_H_
#define	_OverheatingAssistance_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ReducedAggregatedBandwidth-r17.h"
#include <constr_SEQUENCE.h>
#include "MIMO-LayersDL.h"
#include "MIMO-LayersUL.h"

#ifdef __cplusplus
extern "C" {
#endif

/* OverheatingAssistance-r17 */
typedef struct OverheatingAssistance_r17 {
	struct OverheatingAssistance_r17__reducedMaxBW_FR2_2_r17 {
		ReducedAggregatedBandwidth_r17_t	 reducedBW_FR2_2_DL_r17;
		ReducedAggregatedBandwidth_r17_t	 reducedBW_FR2_2_UL_r17;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *reducedMaxBW_FR2_2_r17;
	struct OverheatingAssistance_r17__reducedMaxMIMO_LayersFR2_2 {
		MIMO_LayersDL_t	 reducedMIMO_LayersFR2_2_DL;
		MIMO_LayersUL_t	 reducedMIMO_LayersFR2_2_UL;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *reducedMaxMIMO_LayersFR2_2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OverheatingAssistance_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OverheatingAssistance_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_OverheatingAssistance_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_OverheatingAssistance_r17_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _OverheatingAssistance_r17_H_ */
#include <asn_internal.h>
