/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_PUCCH_ConfigCommon_H_
#define	_PUCCH_ConfigCommon_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PUCCH_ConfigCommon__pucch_GroupHopping {
	PUCCH_ConfigCommon__pucch_GroupHopping_neither	= 0,
	PUCCH_ConfigCommon__pucch_GroupHopping_enable	= 1,
	PUCCH_ConfigCommon__pucch_GroupHopping_disable	= 2
} e_PUCCH_ConfigCommon__pucch_GroupHopping;
typedef enum PUCCH_ConfigCommon__ext1__intra_SlotFH_r17 {
	PUCCH_ConfigCommon__ext1__intra_SlotFH_r17_fromLowerEdge	= 0,
	PUCCH_ConfigCommon__ext1__intra_SlotFH_r17_fromUpperEdge	= 1
} e_PUCCH_ConfigCommon__ext1__intra_SlotFH_r17;
typedef enum PUCCH_ConfigCommon__ext1__additionalPRBOffset_r17 {
	PUCCH_ConfigCommon__ext1__additionalPRBOffset_r17_n2	= 0,
	PUCCH_ConfigCommon__ext1__additionalPRBOffset_r17_n3	= 1,
	PUCCH_ConfigCommon__ext1__additionalPRBOffset_r17_n4	= 2,
	PUCCH_ConfigCommon__ext1__additionalPRBOffset_r17_n6	= 3,
	PUCCH_ConfigCommon__ext1__additionalPRBOffset_r17_n8	= 4,
	PUCCH_ConfigCommon__ext1__additionalPRBOffset_r17_n9	= 5,
	PUCCH_ConfigCommon__ext1__additionalPRBOffset_r17_n10	= 6,
	PUCCH_ConfigCommon__ext1__additionalPRBOffset_r17_n12	= 7
} e_PUCCH_ConfigCommon__ext1__additionalPRBOffset_r17;

/* PUCCH-ConfigCommon */
typedef struct PUCCH_ConfigCommon {
	long	*pucch_ResourceCommon;	/* OPTIONAL */
	long	 pucch_GroupHopping;
	long	*hoppingId;	/* OPTIONAL */
	long	*p0_nominal;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct PUCCH_ConfigCommon__ext1 {
		long	*nrofPRBs;	/* OPTIONAL */
		long	*intra_SlotFH_r17;	/* OPTIONAL */
		long	*pucch_ResourceCommonRedCap_r17;	/* OPTIONAL */
		long	*additionalPRBOffset_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PUCCH_ConfigCommon_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_pucch_GroupHopping_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_intra_SlotFH_r17_12;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_additionalPRBOffset_r17_16;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PUCCH_ConfigCommon;
extern asn_SEQUENCE_specifics_t asn_SPC_PUCCH_ConfigCommon_specs_1;
extern asn_TYPE_member_t asn_MBR_PUCCH_ConfigCommon_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _PUCCH_ConfigCommon_H_ */
#include <asn_internal.h>
