/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_PUCCH_ResourceExt_v1610_H_
#define	_PUCCH_ResourceExt_v1610_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PUCCH_ResourceExt_v1610__interlaceAllocation_r16__interlace0_r16_PR {
	PUCCH_ResourceExt_v1610__interlaceAllocation_r16__interlace0_r16_PR_NOTHING,	/* No components present */
	PUCCH_ResourceExt_v1610__interlaceAllocation_r16__interlace0_r16_PR_scs15,
	PUCCH_ResourceExt_v1610__interlaceAllocation_r16__interlace0_r16_PR_scs30
} PUCCH_ResourceExt_v1610__interlaceAllocation_r16__interlace0_r16_PR;
typedef enum PUCCH_ResourceExt_v1610__format_v1610_PR {
	PUCCH_ResourceExt_v1610__format_v1610_PR_NOTHING,	/* No components present */
	PUCCH_ResourceExt_v1610__format_v1610_PR_interlace1_v1610,
	PUCCH_ResourceExt_v1610__format_v1610_PR_occ_v1610
} PUCCH_ResourceExt_v1610__format_v1610_PR;
typedef enum PUCCH_ResourceExt_v1610__format_v1610__occ_v1610__occ_Length_v1610 {
	PUCCH_ResourceExt_v1610__format_v1610__occ_v1610__occ_Length_v1610_n2	= 0,
	PUCCH_ResourceExt_v1610__format_v1610__occ_v1610__occ_Length_v1610_n4	= 1
} e_PUCCH_ResourceExt_v1610__format_v1610__occ_v1610__occ_Length_v1610;
typedef enum PUCCH_ResourceExt_v1610__format_v1610__occ_v1610__occ_Index_v1610 {
	PUCCH_ResourceExt_v1610__format_v1610__occ_v1610__occ_Index_v1610_n0	= 0,
	PUCCH_ResourceExt_v1610__format_v1610__occ_v1610__occ_Index_v1610_n1	= 1,
	PUCCH_ResourceExt_v1610__format_v1610__occ_v1610__occ_Index_v1610_n2	= 2,
	PUCCH_ResourceExt_v1610__format_v1610__occ_v1610__occ_Index_v1610_n3	= 3
} e_PUCCH_ResourceExt_v1610__format_v1610__occ_v1610__occ_Index_v1610;
typedef enum PUCCH_ResourceExt_v1610__ext1__pucch_RepetitionNrofSlots_r17 {
	PUCCH_ResourceExt_v1610__ext1__pucch_RepetitionNrofSlots_r17_n1	= 0,
	PUCCH_ResourceExt_v1610__ext1__pucch_RepetitionNrofSlots_r17_n2	= 1,
	PUCCH_ResourceExt_v1610__ext1__pucch_RepetitionNrofSlots_r17_n4	= 2,
	PUCCH_ResourceExt_v1610__ext1__pucch_RepetitionNrofSlots_r17_n8	= 3
} e_PUCCH_ResourceExt_v1610__ext1__pucch_RepetitionNrofSlots_r17;

/* PUCCH-ResourceExt-v1610 */
typedef struct PUCCH_ResourceExt_v1610 {
	struct PUCCH_ResourceExt_v1610__interlaceAllocation_r16 {
		long	 rb_SetIndex_r16;
		struct PUCCH_ResourceExt_v1610__interlaceAllocation_r16__interlace0_r16 {
			PUCCH_ResourceExt_v1610__interlaceAllocation_r16__interlace0_r16_PR present;
			union PUCCH_ResourceExt_v1610__interlaceAllocation_r16__interlace0_r16_u {
				long	 scs15;
				long	 scs30;
			} choice;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} interlace0_r16;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *interlaceAllocation_r16;
	struct PUCCH_ResourceExt_v1610__format_v1610 {
		PUCCH_ResourceExt_v1610__format_v1610_PR present;
		union PUCCH_ResourceExt_v1610__format_v1610_u {
			long	 interlace1_v1610;
			struct PUCCH_ResourceExt_v1610__format_v1610__occ_v1610 {
				long	*occ_Length_v1610;	/* OPTIONAL */
				long	*occ_Index_v1610;	/* OPTIONAL */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *occ_v1610;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *format_v1610;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct PUCCH_ResourceExt_v1610__ext1 {
		struct PUCCH_ResourceExt_v1610__ext1__formatExt_v1700 {
			long	 nrofPRBs_r17;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *formatExt_v1700;
		long	*pucch_RepetitionNrofSlots_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PUCCH_ResourceExt_v1610_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_occ_Length_v1610_10;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_occ_Index_v1610_13;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_pucch_RepetitionNrofSlots_r17_22;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PUCCH_ResourceExt_v1610;
extern asn_SEQUENCE_specifics_t asn_SPC_PUCCH_ResourceExt_v1610_specs_1;
extern asn_TYPE_member_t asn_MBR_PUCCH_ResourceExt_v1610_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _PUCCH_ResourceExt_v1610_H_ */
#include <asn_internal.h>
