/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_RA_InformationCommon_r16_H_
#define	_RA_InformationCommon_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ARFCN-ValueNR.h"
#include <NativeInteger.h>
#include "SubcarrierSpacing.h"
#include <NativeEnumerated.h>
#include "PerRAInfoList-r16.h"
#include <constr_SEQUENCE.h>
#include "RSRP-Range.h"
#include <BIT_STRING.h>
#include "SIB-Type-r17.h"
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include "SSB-Index.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RA_InformationCommon_r16__msg1_FDM_r16 {
	RA_InformationCommon_r16__msg1_FDM_r16_one	= 0,
	RA_InformationCommon_r16__msg1_FDM_r16_two	= 1,
	RA_InformationCommon_r16__msg1_FDM_r16_four	= 2,
	RA_InformationCommon_r16__msg1_FDM_r16_eight	= 3
} e_RA_InformationCommon_r16__msg1_FDM_r16;
typedef enum RA_InformationCommon_r16__msg1_FDMCFRA_r16 {
	RA_InformationCommon_r16__msg1_FDMCFRA_r16_one	= 0,
	RA_InformationCommon_r16__msg1_FDMCFRA_r16_two	= 1,
	RA_InformationCommon_r16__msg1_FDMCFRA_r16_four	= 2,
	RA_InformationCommon_r16__msg1_FDMCFRA_r16_eight	= 3
} e_RA_InformationCommon_r16__msg1_FDMCFRA_r16;
typedef enum RA_InformationCommon_r16__ext2__msg1_SCS_From_prach_ConfigurationIndex_r16 {
	RA_InformationCommon_r16__ext2__msg1_SCS_From_prach_ConfigurationIndex_r16_kHz1dot25	= 0,
	RA_InformationCommon_r16__ext2__msg1_SCS_From_prach_ConfigurationIndex_r16_kHz5	= 1,
	RA_InformationCommon_r16__ext2__msg1_SCS_From_prach_ConfigurationIndex_r16_spare2	= 2,
	RA_InformationCommon_r16__ext2__msg1_SCS_From_prach_ConfigurationIndex_r16_spare1	= 3
} e_RA_InformationCommon_r16__ext2__msg1_SCS_From_prach_ConfigurationIndex_r16;
typedef enum RA_InformationCommon_r16__ext3__msg1_SCS_From_prach_ConfigurationIndexCFRA_r16 {
	RA_InformationCommon_r16__ext3__msg1_SCS_From_prach_ConfigurationIndexCFRA_r16_kHz1dot25	= 0,
	RA_InformationCommon_r16__ext3__msg1_SCS_From_prach_ConfigurationIndexCFRA_r16_kHz5	= 1,
	RA_InformationCommon_r16__ext3__msg1_SCS_From_prach_ConfigurationIndexCFRA_r16_spare2	= 2,
	RA_InformationCommon_r16__ext3__msg1_SCS_From_prach_ConfigurationIndexCFRA_r16_spare1	= 3
} e_RA_InformationCommon_r16__ext3__msg1_SCS_From_prach_ConfigurationIndexCFRA_r16;
typedef enum RA_InformationCommon_r16__ext4__msgA_RO_FDM_r17 {
	RA_InformationCommon_r16__ext4__msgA_RO_FDM_r17_one	= 0,
	RA_InformationCommon_r16__ext4__msgA_RO_FDM_r17_two	= 1,
	RA_InformationCommon_r16__ext4__msgA_RO_FDM_r17_four	= 2,
	RA_InformationCommon_r16__ext4__msgA_RO_FDM_r17_eight	= 3
} e_RA_InformationCommon_r16__ext4__msgA_RO_FDM_r17;
typedef enum RA_InformationCommon_r16__ext4__msgA_RO_FDMCFRA_r17 {
	RA_InformationCommon_r16__ext4__msgA_RO_FDMCFRA_r17_one	= 0,
	RA_InformationCommon_r16__ext4__msgA_RO_FDMCFRA_r17_two	= 1,
	RA_InformationCommon_r16__ext4__msgA_RO_FDMCFRA_r17_four	= 2,
	RA_InformationCommon_r16__ext4__msgA_RO_FDMCFRA_r17_eight	= 3
} e_RA_InformationCommon_r16__ext4__msgA_RO_FDMCFRA_r17;
typedef enum RA_InformationCommon_r16__ext4__msgA_SCS_From_prach_ConfigurationIndex_r17 {
	RA_InformationCommon_r16__ext4__msgA_SCS_From_prach_ConfigurationIndex_r17_kHz1dot25	= 0,
	RA_InformationCommon_r16__ext4__msgA_SCS_From_prach_ConfigurationIndex_r17_kHz5	= 1,
	RA_InformationCommon_r16__ext4__msgA_SCS_From_prach_ConfigurationIndex_r17_spare2	= 2,
	RA_InformationCommon_r16__ext4__msgA_SCS_From_prach_ConfigurationIndex_r17_spare1	= 3
} e_RA_InformationCommon_r16__ext4__msgA_SCS_From_prach_ConfigurationIndex_r17;
typedef enum RA_InformationCommon_r16__ext4__msgA_TransMax_r17 {
	RA_InformationCommon_r16__ext4__msgA_TransMax_r17_n1	= 0,
	RA_InformationCommon_r16__ext4__msgA_TransMax_r17_n2	= 1,
	RA_InformationCommon_r16__ext4__msgA_TransMax_r17_n4	= 2,
	RA_InformationCommon_r16__ext4__msgA_TransMax_r17_n6	= 3,
	RA_InformationCommon_r16__ext4__msgA_TransMax_r17_n8	= 4,
	RA_InformationCommon_r16__ext4__msgA_TransMax_r17_n10	= 5,
	RA_InformationCommon_r16__ext4__msgA_TransMax_r17_n20	= 6,
	RA_InformationCommon_r16__ext4__msgA_TransMax_r17_n50	= 7,
	RA_InformationCommon_r16__ext4__msgA_TransMax_r17_n100	= 8,
	RA_InformationCommon_r16__ext4__msgA_TransMax_r17_n200	= 9
} e_RA_InformationCommon_r16__ext4__msgA_TransMax_r17;
typedef enum RA_InformationCommon_r16__ext4__nrofMsgA_PO_FDM_r17 {
	RA_InformationCommon_r16__ext4__nrofMsgA_PO_FDM_r17_one	= 0,
	RA_InformationCommon_r16__ext4__nrofMsgA_PO_FDM_r17_two	= 1,
	RA_InformationCommon_r16__ext4__nrofMsgA_PO_FDM_r17_four	= 2,
	RA_InformationCommon_r16__ext4__nrofMsgA_PO_FDM_r17_eight	= 3
} e_RA_InformationCommon_r16__ext4__nrofMsgA_PO_FDM_r17;
typedef enum RA_InformationCommon_r16__ext4__onDemandSISuccess_r17 {
	RA_InformationCommon_r16__ext4__onDemandSISuccess_r17_true	= 0
} e_RA_InformationCommon_r16__ext4__onDemandSISuccess_r17;

/* Forward declarations */
struct PerRAInfoList_v1660;

/* RA-InformationCommon-r16 */
typedef struct RA_InformationCommon_r16 {
	ARFCN_ValueNR_t	 absoluteFrequencyPointA_r16;
	long	 locationAndBandwidth_r16;
	SubcarrierSpacing_t	 subcarrierSpacing_r16;
	long	*msg1_FrequencyStart_r16;	/* OPTIONAL */
	long	*msg1_FrequencyStartCFRA_r16;	/* OPTIONAL */
	SubcarrierSpacing_t	*msg1_SubcarrierSpacing_r16;	/* OPTIONAL */
	SubcarrierSpacing_t	*msg1_SubcarrierSpacingCFRA_r16;	/* OPTIONAL */
	long	*msg1_FDM_r16;	/* OPTIONAL */
	long	*msg1_FDMCFRA_r16;	/* OPTIONAL */
	PerRAInfoList_r16_t	 perRAInfoList_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct RA_InformationCommon_r16__ext1 {
		struct PerRAInfoList_v1660	*perRAInfoList_v1660;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct RA_InformationCommon_r16__ext2 {
		long	*msg1_SCS_From_prach_ConfigurationIndex_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	struct RA_InformationCommon_r16__ext3 {
		long	*msg1_SCS_From_prach_ConfigurationIndexCFRA_r16;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext3;
	struct RA_InformationCommon_r16__ext4 {
		long	*msgA_RO_FrequencyStart_r17;	/* OPTIONAL */
		long	*msgA_RO_FrequencyStartCFRA_r17;	/* OPTIONAL */
		SubcarrierSpacing_t	*msgA_SubcarrierSpacing_r17;	/* OPTIONAL */
		long	*msgA_RO_FDM_r17;	/* OPTIONAL */
		long	*msgA_RO_FDMCFRA_r17;	/* OPTIONAL */
		long	*msgA_SCS_From_prach_ConfigurationIndex_r17;	/* OPTIONAL */
		long	*msgA_TransMax_r17;	/* OPTIONAL */
		long	*msgA_MCS_r17;	/* OPTIONAL */
		long	*nrofPRBs_PerMsgA_PO_r17;	/* OPTIONAL */
		long	*msgA_PUSCH_TimeDomainAllocation_r17;	/* OPTIONAL */
		long	*frequencyStartMsgA_PUSCH_r17;	/* OPTIONAL */
		long	*nrofMsgA_PO_FDM_r17;	/* OPTIONAL */
		RSRP_Range_t	*dlPathlossRSRP_r17;	/* OPTIONAL */
		struct RA_InformationCommon_r16__ext4__intendedSIBs_r17 {
			A_SEQUENCE_OF(SIB_Type_r17_t) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *intendedSIBs_r17;
		struct RA_InformationCommon_r16__ext4__ssbsForSI_Acquisition_r17 {
			A_SEQUENCE_OF(SSB_Index_t) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *ssbsForSI_Acquisition_r17;
		BIT_STRING_t	*msgA_PUSCH_PayloadSize_r17;	/* OPTIONAL */
		long	*onDemandSISuccess_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext4;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RA_InformationCommon_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_msg1_FDM_r16_9;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_msg1_FDMCFRA_r16_14;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_msg1_SCS_From_prach_ConfigurationIndex_r16_24;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_msg1_SCS_From_prach_ConfigurationIndexCFRA_r16_30;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_msgA_RO_FDM_r17_39;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_msgA_RO_FDMCFRA_r17_44;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_msgA_SCS_From_prach_ConfigurationIndex_r17_49;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_msgA_TransMax_r17_54;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_nrofMsgA_PO_FDM_r17_69;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_onDemandSISuccess_r17_80;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RA_InformationCommon_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_RA_InformationCommon_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_RA_InformationCommon_r16_1[14];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PerRAInfoList-v1660.h"

#endif	/* _RA_InformationCommon_r16_H_ */
#include <asn_internal.h>
