/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_RadioBearerConfig_H_
#define	_RadioBearerConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RadioBearerConfig__srb3_ToRelease {
	RadioBearerConfig__srb3_ToRelease_true	= 0
} e_RadioBearerConfig__srb3_ToRelease;
typedef enum RadioBearerConfig__ext1__srb4_ToRelease_r17 {
	RadioBearerConfig__ext1__srb4_ToRelease_r17_true	= 0
} e_RadioBearerConfig__ext1__srb4_ToRelease_r17;

/* Forward declarations */
struct SRB_ToAddModList;
struct DRB_ToAddModList;
struct DRB_ToReleaseList;
struct SecurityConfig;
struct MRB_ToAddModList_r17;
struct MRB_ToReleaseList_r17;
struct SRB_ToAddMod;

/* RadioBearerConfig */
typedef struct RadioBearerConfig {
	struct SRB_ToAddModList	*srb_ToAddModList;	/* OPTIONAL */
	long	*srb3_ToRelease;	/* OPTIONAL */
	struct DRB_ToAddModList	*drb_ToAddModList;	/* OPTIONAL */
	struct DRB_ToReleaseList	*drb_ToReleaseList;	/* OPTIONAL */
	struct SecurityConfig	*securityConfig;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct RadioBearerConfig__ext1 {
		struct MRB_ToAddModList_r17	*mrb_ToAddModList_r17;	/* OPTIONAL */
		struct MRB_ToReleaseList_r17	*mrb_ToReleaseList_r17;	/* OPTIONAL */
		struct SRB_ToAddMod	*srb4_ToAddMod_r17;	/* OPTIONAL */
		long	*srb4_ToRelease_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RadioBearerConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_srb3_ToRelease_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_srb4_ToRelease_r17_13;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RadioBearerConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_RadioBearerConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_RadioBearerConfig_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SRB-ToAddModList.h"
#include "DRB-ToAddModList.h"
#include "DRB-ToReleaseList.h"
#include "SecurityConfig.h"
#include "MRB-ToAddModList-r17.h"
#include "MRB-ToReleaseList-r17.h"
#include "SRB-ToAddMod.h"

#endif	/* _RadioBearerConfig_H_ */
#include <asn_internal.h>
