/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_RedCapParameters_r17_H_
#define	_RedCapParameters_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RedCapParameters_r17__supportOfRedCap_r17 {
	RedCapParameters_r17__supportOfRedCap_r17_supported	= 0
} e_RedCapParameters_r17__supportOfRedCap_r17;
typedef enum RedCapParameters_r17__supportOf16DRB_RedCap_r17 {
	RedCapParameters_r17__supportOf16DRB_RedCap_r17_supported	= 0
} e_RedCapParameters_r17__supportOf16DRB_RedCap_r17;

/* RedCapParameters-r17 */
typedef struct RedCapParameters_r17 {
	long	*supportOfRedCap_r17;	/* OPTIONAL */
	long	*supportOf16DRB_RedCap_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RedCapParameters_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_supportOfRedCap_r17_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_supportOf16DRB_RedCap_r17_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RedCapParameters_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_RedCapParameters_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_RedCapParameters_r17_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RedCapParameters_r17_H_ */
#include <asn_internal.h>
