/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_RLC_BearerConfig_H_
#define	_RLC_BearerConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LogicalChannelIdentity.h"
#include <NativeEnumerated.h>
#include "SRB-Identity.h"
#include "DRB-Identity.h"
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include "LogicalChannelIdentityExt-r17.h"
#include "SRB-Identity-v1700.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RLC_BearerConfig__servedRadioBearer_PR {
	RLC_BearerConfig__servedRadioBearer_PR_NOTHING,	/* No components present */
	RLC_BearerConfig__servedRadioBearer_PR_srb_Identity,
	RLC_BearerConfig__servedRadioBearer_PR_drb_Identity
} RLC_BearerConfig__servedRadioBearer_PR;
typedef enum RLC_BearerConfig__reestablishRLC {
	RLC_BearerConfig__reestablishRLC_true	= 0
} e_RLC_BearerConfig__reestablishRLC;

/* Forward declarations */
struct RLC_Config;
struct LogicalChannelConfig;
struct RLC_Config_v1610;
struct RLC_Config_v1700;
struct MulticastRLC_BearerConfig_r17;

/* RLC-BearerConfig */
typedef struct RLC_BearerConfig {
	LogicalChannelIdentity_t	 logicalChannelIdentity;
	struct RLC_BearerConfig__servedRadioBearer {
		RLC_BearerConfig__servedRadioBearer_PR present;
		union RLC_BearerConfig__servedRadioBearer_u {
			SRB_Identity_t	 srb_Identity;
			DRB_Identity_t	 drb_Identity;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *servedRadioBearer;
	long	*reestablishRLC;	/* OPTIONAL */
	struct RLC_Config	*rlc_Config;	/* OPTIONAL */
	struct LogicalChannelConfig	*mac_LogicalChannelConfig;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct RLC_BearerConfig__ext1 {
		struct RLC_Config_v1610	*rlc_Config_v1610;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct RLC_BearerConfig__ext2 {
		struct RLC_Config_v1700	*rlc_Config_v1700;	/* OPTIONAL */
		LogicalChannelIdentityExt_r17_t	*logicalChannelIdentityExt_r17;	/* OPTIONAL */
		struct MulticastRLC_BearerConfig_r17	*multicastRLC_BearerConfig_r17;	/* OPTIONAL */
		SRB_Identity_v1700_t	*servedRadioBearerSRB4_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RLC_BearerConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_reestablishRLC_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RLC_BearerConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_RLC_BearerConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_RLC_BearerConfig_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RLC-Config.h"
#include "LogicalChannelConfig.h"
#include "RLC-Config-v1610.h"
#include "RLC-Config-v1700.h"
#include "MulticastRLC-BearerConfig-r17.h"

#endif	/* _RLC_BearerConfig_H_ */
#include <asn_internal.h>
