/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_RLF_Report_r16_H_
#define	_RLF_Report_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "MeasResultRLFNR-r16.h"
#include "RNTI-Value.h"
#include "TimeUntilReconnection-r16.h"
#include <NativeInteger.h>
#include "TimeSinceFailure-r16.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>
#include <BIT_STRING.h>
#include "TimeConnSourceDAPS-Failure-r17.h"
#include "TimeSinceCHO-Reconfig-r17.h"
#include "CGI-InfoEUTRALogging.h"
#include <OCTET_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RLF_Report_r16_PR {
	RLF_Report_r16_PR_NOTHING,	/* No components present */
	RLF_Report_r16_PR_nr_RLF_Report_r16,
	RLF_Report_r16_PR_eutra_RLF_Report_r16
} RLF_Report_r16_PR;
typedef enum RLF_Report_r16__nr_RLF_Report_r16__previousPCellId_r16_PR {
	RLF_Report_r16__nr_RLF_Report_r16__previousPCellId_r16_PR_NOTHING,	/* No components present */
	RLF_Report_r16__nr_RLF_Report_r16__previousPCellId_r16_PR_nrPreviousCell_r16,
	RLF_Report_r16__nr_RLF_Report_r16__previousPCellId_r16_PR_eutraPreviousCell_r16
} RLF_Report_r16__nr_RLF_Report_r16__previousPCellId_r16_PR;
typedef enum RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16_PR {
	RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16_PR_NOTHING,	/* No components present */
	RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16_PR_nrFailedPCellId_r16,
	RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16_PR_eutraFailedPCellId_r16
} RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16_PR;
typedef enum RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__nrFailedPCellId_r16_PR {
	RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__nrFailedPCellId_r16_PR_NOTHING,	/* No components present */
	RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__nrFailedPCellId_r16_PR_cellGlobalId_r16,
	RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__nrFailedPCellId_r16_PR_pci_arfcn_r16
} RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__nrFailedPCellId_r16_PR;
typedef enum RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__eutraFailedPCellId_r16_PR {
	RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__eutraFailedPCellId_r16_PR_NOTHING,	/* No components present */
	RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__eutraFailedPCellId_r16_PR_cellGlobalId_r16,
	RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__eutraFailedPCellId_r16_PR_pci_arfcn_r16
} RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__eutraFailedPCellId_r16_PR;
typedef enum RLF_Report_r16__nr_RLF_Report_r16__reconnectCellId_r16_PR {
	RLF_Report_r16__nr_RLF_Report_r16__reconnectCellId_r16_PR_NOTHING,	/* No components present */
	RLF_Report_r16__nr_RLF_Report_r16__reconnectCellId_r16_PR_nrReconnectCellId_r16,
	RLF_Report_r16__nr_RLF_Report_r16__reconnectCellId_r16_PR_eutraReconnectCellId_r16
} RLF_Report_r16__nr_RLF_Report_r16__reconnectCellId_r16_PR;
typedef enum RLF_Report_r16__nr_RLF_Report_r16__connectionFailureType_r16 {
	RLF_Report_r16__nr_RLF_Report_r16__connectionFailureType_r16_rlf	= 0,
	RLF_Report_r16__nr_RLF_Report_r16__connectionFailureType_r16_hof	= 1
} e_RLF_Report_r16__nr_RLF_Report_r16__connectionFailureType_r16;
typedef enum RLF_Report_r16__nr_RLF_Report_r16__rlf_Cause_r16 {
	RLF_Report_r16__nr_RLF_Report_r16__rlf_Cause_r16_t310_Expiry	= 0,
	RLF_Report_r16__nr_RLF_Report_r16__rlf_Cause_r16_randomAccessProblem	= 1,
	RLF_Report_r16__nr_RLF_Report_r16__rlf_Cause_r16_rlc_MaxNumRetx	= 2,
	RLF_Report_r16__nr_RLF_Report_r16__rlf_Cause_r16_beamFailureRecoveryFailure	= 3,
	RLF_Report_r16__nr_RLF_Report_r16__rlf_Cause_r16_lbtFailure_r16	= 4,
	RLF_Report_r16__nr_RLF_Report_r16__rlf_Cause_r16_bh_rlfRecoveryFailure	= 5,
	RLF_Report_r16__nr_RLF_Report_r16__rlf_Cause_r16_t312_expiry_r17	= 6,
	RLF_Report_r16__nr_RLF_Report_r16__rlf_Cause_r16_spare1	= 7
} e_RLF_Report_r16__nr_RLF_Report_r16__rlf_Cause_r16;
typedef enum RLF_Report_r16__nr_RLF_Report_r16__noSuitableCellFound_r16 {
	RLF_Report_r16__nr_RLF_Report_r16__noSuitableCellFound_r16_true	= 0
} e_RLF_Report_r16__nr_RLF_Report_r16__noSuitableCellFound_r16;
typedef enum RLF_Report_r16__nr_RLF_Report_r16__ext2__lastHO_Type_r17 {
	RLF_Report_r16__nr_RLF_Report_r16__ext2__lastHO_Type_r17_cho	= 0,
	RLF_Report_r16__nr_RLF_Report_r16__ext2__lastHO_Type_r17_daps	= 1,
	RLF_Report_r16__nr_RLF_Report_r16__ext2__lastHO_Type_r17_spare2	= 2,
	RLF_Report_r16__nr_RLF_Report_r16__ext2__lastHO_Type_r17_spare1	= 3
} e_RLF_Report_r16__nr_RLF_Report_r16__ext2__lastHO_Type_r17;
typedef enum RLF_Report_r16__nr_RLF_Report_r16__ext2__choCellId_r17_PR {
	RLF_Report_r16__nr_RLF_Report_r16__ext2__choCellId_r17_PR_NOTHING,	/* No components present */
	RLF_Report_r16__nr_RLF_Report_r16__ext2__choCellId_r17_PR_cellGlobalId_r17,
	RLF_Report_r16__nr_RLF_Report_r16__ext2__choCellId_r17_PR_pci_arfcn_r17
} RLF_Report_r16__nr_RLF_Report_r16__ext2__choCellId_r17_PR;

/* Forward declarations */
struct CGI_Info_Logging_r16;
struct LocationInfo_r16;
struct RA_InformationCommon_r16;
struct MeasResultList2NR_r16;
struct MeasResultList2EUTRA_r16;
struct CGI_InfoEUTRALogging;
struct PCI_ARFCN_NR_r16;
struct PCI_ARFCN_EUTRA_r16;
struct ChoCandidateCellList_r17;

/* RLF-Report-r16 */
typedef struct RLF_Report_r16 {
	RLF_Report_r16_PR present;
	union RLF_Report_r16_u {
		struct RLF_Report_r16__nr_RLF_Report_r16 {
			MeasResultRLFNR_r16_t	 measResultLastServCell_r16;
			struct RLF_Report_r16__nr_RLF_Report_r16__measResultNeighCells_r16 {
				struct MeasResultList2NR_r16	*measResultListNR_r16;	/* OPTIONAL */
				struct MeasResultList2EUTRA_r16	*measResultListEUTRA_r16;	/* OPTIONAL */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *measResultNeighCells_r16;
			RNTI_Value_t	 c_RNTI_r16;
			struct RLF_Report_r16__nr_RLF_Report_r16__previousPCellId_r16 {
				RLF_Report_r16__nr_RLF_Report_r16__previousPCellId_r16_PR present;
				union RLF_Report_r16__nr_RLF_Report_r16__previousPCellId_r16_u {
					struct CGI_Info_Logging_r16	*nrPreviousCell_r16;
					struct CGI_InfoEUTRALogging	*eutraPreviousCell_r16;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *previousPCellId_r16;
			struct RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16 {
				RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16_PR present;
				union RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16_u {
					struct RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__nrFailedPCellId_r16 {
						RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__nrFailedPCellId_r16_PR present;
						union RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__nrFailedPCellId_r16_u {
							struct CGI_Info_Logging_r16	*cellGlobalId_r16;
							struct PCI_ARFCN_NR_r16	*pci_arfcn_r16;
						} choice;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *nrFailedPCellId_r16;
					struct RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__eutraFailedPCellId_r16 {
						RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__eutraFailedPCellId_r16_PR present;
						union RLF_Report_r16__nr_RLF_Report_r16__failedPCellId_r16__eutraFailedPCellId_r16_u {
							struct CGI_InfoEUTRALogging	*cellGlobalId_r16;
							struct PCI_ARFCN_EUTRA_r16	*pci_arfcn_r16;
						} choice;
						
						/* Context for parsing across buffer boundaries */
						asn_struct_ctx_t _asn_ctx;
					} *eutraFailedPCellId_r16;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} failedPCellId_r16;
			struct RLF_Report_r16__nr_RLF_Report_r16__reconnectCellId_r16 {
				RLF_Report_r16__nr_RLF_Report_r16__reconnectCellId_r16_PR present;
				union RLF_Report_r16__nr_RLF_Report_r16__reconnectCellId_r16_u {
					struct CGI_Info_Logging_r16	*nrReconnectCellId_r16;
					struct CGI_InfoEUTRALogging	*eutraReconnectCellId_r16;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *reconnectCellId_r16;
			TimeUntilReconnection_r16_t	*timeUntilReconnection_r16;	/* OPTIONAL */
			struct CGI_Info_Logging_r16	*reestablishmentCellId_r16;	/* OPTIONAL */
			long	*timeConnFailure_r16;	/* OPTIONAL */
			TimeSinceFailure_r16_t	 timeSinceFailure_r16;
			long	 connectionFailureType_r16;
			long	 rlf_Cause_r16;
			struct LocationInfo_r16	*locationInfo_r16;	/* OPTIONAL */
			long	*noSuitableCellFound_r16;	/* OPTIONAL */
			struct RA_InformationCommon_r16	*ra_InformationCommon_r16;	/* OPTIONAL */
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			struct RLF_Report_r16__nr_RLF_Report_r16__ext1 {
				BIT_STRING_t	*csi_rsRLMConfigBitmap_v1650;	/* OPTIONAL */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *ext1;
			struct RLF_Report_r16__nr_RLF_Report_r16__ext2 {
				long	*lastHO_Type_r17;	/* OPTIONAL */
				TimeConnSourceDAPS_Failure_r17_t	*timeConnSourceDAPS_Failure_r17;	/* OPTIONAL */
				TimeSinceCHO_Reconfig_r17_t	*timeSinceCHO_Reconfig_r17;	/* OPTIONAL */
				struct RLF_Report_r16__nr_RLF_Report_r16__ext2__choCellId_r17 {
					RLF_Report_r16__nr_RLF_Report_r16__ext2__choCellId_r17_PR present;
					union RLF_Report_r16__nr_RLF_Report_r16__ext2__choCellId_r17_u {
						struct CGI_Info_Logging_r16	*cellGlobalId_r17;
						struct PCI_ARFCN_NR_r16	*pci_arfcn_r17;
					} choice;
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} *choCellId_r17;
				struct ChoCandidateCellList_r17	*choCandidateCellList_r17;	/* OPTIONAL */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *ext2;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *nr_RLF_Report_r16;
		struct RLF_Report_r16__eutra_RLF_Report_r16 {
			CGI_InfoEUTRALogging_t	 failedPCellId_EUTRA;
			OCTET_STRING_t	 measResult_RLF_Report_EUTRA_r16;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			struct RLF_Report_r16__eutra_RLF_Report_r16__ext1 {
				OCTET_STRING_t	*measResult_RLF_Report_EUTRA_v1690;	/* OPTIONAL */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *ext1;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *eutra_RLF_Report_r16;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RLF_Report_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_connectionFailureType_r16_25;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_rlf_Cause_r16_28;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_noSuitableCellFound_r16_38;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_lastHO_Type_r17_45;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RLF_Report_r16;
extern asn_CHOICE_specifics_t asn_SPC_RLF_Report_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_RLF_Report_r16_1[2];
extern asn_per_constraints_t asn_PER_type_RLF_Report_r16_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CGI-Info-Logging-r16.h"
#include "LocationInfo-r16.h"
#include "RA-InformationCommon-r16.h"
#include "MeasResultList2NR-r16.h"
#include "MeasResultList2EUTRA-r16.h"
#include "CGI-InfoEUTRALogging.h"
#include "PCI-ARFCN-NR-r16.h"
#include "PCI-ARFCN-EUTRA-r16.h"
#include "ChoCandidateCellList-r17.h"

#endif	/* _RLF_Report_r16_H_ */
#include <asn_internal.h>
