/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_RRM_MeasRelaxationReportingConfig_r17_H_
#define	_RRM_MeasRelaxationReportingConfig_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RRM_MeasRelaxationReportingConfig_r17__s_SearchDeltaP_Stationary_r17 {
	RRM_MeasRelaxationReportingConfig_r17__s_SearchDeltaP_Stationary_r17_dB2	= 0,
	RRM_MeasRelaxationReportingConfig_r17__s_SearchDeltaP_Stationary_r17_dB3	= 1,
	RRM_MeasRelaxationReportingConfig_r17__s_SearchDeltaP_Stationary_r17_dB6	= 2,
	RRM_MeasRelaxationReportingConfig_r17__s_SearchDeltaP_Stationary_r17_dB9	= 3,
	RRM_MeasRelaxationReportingConfig_r17__s_SearchDeltaP_Stationary_r17_dB12	= 4,
	RRM_MeasRelaxationReportingConfig_r17__s_SearchDeltaP_Stationary_r17_dB15	= 5,
	RRM_MeasRelaxationReportingConfig_r17__s_SearchDeltaP_Stationary_r17_spare2	= 6,
	RRM_MeasRelaxationReportingConfig_r17__s_SearchDeltaP_Stationary_r17_spare1	= 7
} e_RRM_MeasRelaxationReportingConfig_r17__s_SearchDeltaP_Stationary_r17;
typedef enum RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17 {
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_s5	= 0,
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_s10	= 1,
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_s20	= 2,
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_s30	= 3,
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_s60	= 4,
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_s120	= 5,
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_s180	= 6,
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_s240	= 7,
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_s300	= 8,
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_spare7	= 9,
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_spare6	= 10,
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_spare5	= 11,
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_spare4	= 12,
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_spare3	= 13,
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_spare2	= 14,
	RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17_spare1	= 15
} e_RRM_MeasRelaxationReportingConfig_r17__t_SearchDeltaP_Stationary_r17;

/* RRM-MeasRelaxationReportingConfig-r17 */
typedef struct RRM_MeasRelaxationReportingConfig_r17 {
	long	 s_SearchDeltaP_Stationary_r17;
	long	 t_SearchDeltaP_Stationary_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RRM_MeasRelaxationReportingConfig_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_s_SearchDeltaP_Stationary_r17_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_t_SearchDeltaP_Stationary_r17_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_RRM_MeasRelaxationReportingConfig_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_RRM_MeasRelaxationReportingConfig_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_RRM_MeasRelaxationReportingConfig_r17_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _RRM_MeasRelaxationReportingConfig_r17_H_ */
#include <asn_internal.h>
