/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_SchedulingRequestToAddModExt_v1700_H_
#define	_SchedulingRequestToAddModExt_v1700_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700 {
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_ms192	= 0,
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_ms256	= 1,
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_ms320	= 2,
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_ms384	= 3,
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_ms448	= 4,
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_ms512	= 5,
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_ms576	= 6,
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_ms640	= 7,
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_ms1082	= 8,
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_spare7	= 9,
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_spare6	= 10,
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_spare5	= 11,
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_spare4	= 12,
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_spare3	= 13,
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_spare2	= 14,
	SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700_spare1	= 15
} e_SchedulingRequestToAddModExt_v1700__sr_ProhibitTimer_v1700;

/* SchedulingRequestToAddModExt-v1700 */
typedef struct SchedulingRequestToAddModExt_v1700 {
	long	*sr_ProhibitTimer_v1700;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SchedulingRequestToAddModExt_v1700_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_sr_ProhibitTimer_v1700_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SchedulingRequestToAddModExt_v1700;
extern asn_SEQUENCE_specifics_t asn_SPC_SchedulingRequestToAddModExt_v1700_specs_1;
extern asn_TYPE_member_t asn_MBR_SchedulingRequestToAddModExt_v1700_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _SchedulingRequestToAddModExt_v1700_H_ */
#include <asn_internal.h>
