/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_SearchSpaceExt_v1700_H_
#define	_SearchSpaceExt_v1700_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>
#include <NativeEnumerated.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SearchSpaceExt_v1700__monitoringSlotPeriodicityAndOffset_v1710_PR {
	SearchSpaceExt_v1700__monitoringSlotPeriodicityAndOffset_v1710_PR_NOTHING,	/* No components present */
	SearchSpaceExt_v1700__monitoringSlotPeriodicityAndOffset_v1710_PR_sl32,
	SearchSpaceExt_v1700__monitoringSlotPeriodicityAndOffset_v1710_PR_sl64,
	SearchSpaceExt_v1700__monitoringSlotPeriodicityAndOffset_v1710_PR_sl128,
	SearchSpaceExt_v1700__monitoringSlotPeriodicityAndOffset_v1710_PR_sl5120,
	SearchSpaceExt_v1700__monitoringSlotPeriodicityAndOffset_v1710_PR_sl10240,
	SearchSpaceExt_v1700__monitoringSlotPeriodicityAndOffset_v1710_PR_sl20480
} SearchSpaceExt_v1700__monitoringSlotPeriodicityAndOffset_v1710_PR;
typedef enum SearchSpaceExt_v1700__monitoringSlotsWithinSlotGroup_r17_PR {
	SearchSpaceExt_v1700__monitoringSlotsWithinSlotGroup_r17_PR_NOTHING,	/* No components present */
	SearchSpaceExt_v1700__monitoringSlotsWithinSlotGroup_r17_PR_slotGroupLength4_r17,
	SearchSpaceExt_v1700__monitoringSlotsWithinSlotGroup_r17_PR_slotGroupLength8_r17
} SearchSpaceExt_v1700__monitoringSlotsWithinSlotGroup_r17_PR;
typedef enum SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel4_r17 {
	SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel4_r17_n0	= 0,
	SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel4_r17_n1	= 1,
	SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel4_r17_n2	= 2,
	SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel4_r17_n3	= 3,
	SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel4_r17_n4	= 4
} e_SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel4_r17;
typedef enum SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel8_r17 {
	SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel8_r17_n0	= 0,
	SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel8_r17_n1	= 1,
	SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel8_r17_n2	= 2
} e_SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel8_r17;
typedef enum SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel16_r17 {
	SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel16_r17_n0	= 0,
	SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel16_r17_n1	= 1
} e_SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17__aggregationLevel16_r17;

/* SearchSpaceExt-v1700 */
typedef struct SearchSpaceExt_v1700 {
	struct SearchSpaceExt_v1700__monitoringSlotPeriodicityAndOffset_v1710 {
		SearchSpaceExt_v1700__monitoringSlotPeriodicityAndOffset_v1710_PR present;
		union SearchSpaceExt_v1700__monitoringSlotPeriodicityAndOffset_v1710_u {
			long	 sl32;
			long	 sl64;
			long	 sl128;
			long	 sl5120;
			long	 sl10240;
			long	 sl20480;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *monitoringSlotPeriodicityAndOffset_v1710;
	struct SearchSpaceExt_v1700__monitoringSlotsWithinSlotGroup_r17 {
		SearchSpaceExt_v1700__monitoringSlotsWithinSlotGroup_r17_PR present;
		union SearchSpaceExt_v1700__monitoringSlotsWithinSlotGroup_r17_u {
			BIT_STRING_t	 slotGroupLength4_r17;
			BIT_STRING_t	 slotGroupLength8_r17;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *monitoringSlotsWithinSlotGroup_r17;
	long	*duration_r17;	/* OPTIONAL */
	struct SearchSpaceExt_v1700__searchSpaceType_r17 {
		struct SearchSpaceExt_v1700__searchSpaceType_r17__common_r17 {
			struct SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format4_0_r17 {
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *dci_Format4_0_r17;
			struct SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format4_1_r17 {
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *dci_Format4_1_r17;
			struct SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format4_2_r17 {
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *dci_Format4_2_r17;
			struct SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format4_1_AndFormat4_2_r17 {
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *dci_Format4_1_AndFormat4_2_r17;
			struct SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17 {
				struct SearchSpaceExt_v1700__searchSpaceType_r17__common_r17__dci_Format2_7_r17__nrofCandidates_PEI_r17 {
					long	*aggregationLevel4_r17;	/* OPTIONAL */
					long	*aggregationLevel8_r17;	/* OPTIONAL */
					long	*aggregationLevel16_r17;	/* OPTIONAL */
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} nrofCandidates_PEI_r17;
				/*
				 * This type is extensible,
				 * possible extensions are below.
				 */
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *dci_Format2_7_r17;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} common_r17;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *searchSpaceType_r17;
	struct SearchSpaceExt_v1700__searchSpaceGroupIdList_r17 {
		A_SEQUENCE_OF(long) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *searchSpaceGroupIdList_r17;
	long	*searchSpaceLinkingId_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SearchSpaceExt_v1700_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_aggregationLevel4_r17_25;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_aggregationLevel8_r17_31;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_aggregationLevel16_r17_35;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SearchSpaceExt_v1700;
extern asn_SEQUENCE_specifics_t asn_SPC_SearchSpaceExt_v1700_specs_1;
extern asn_TYPE_member_t asn_MBR_SearchSpaceExt_v1700_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _SearchSpaceExt_v1700_H_ */
#include <asn_internal.h>
