/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_SIB17_r17_H_
#define	_SIB17_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SIB17_r17__segmentType_r17 {
	SIB17_r17__segmentType_r17_notLastSegment	= 0,
	SIB17_r17__segmentType_r17_lastSegment	= 1
} e_SIB17_r17__segmentType_r17;

/* SIB17-r17 */
typedef struct SIB17_r17 {
	long	 segmentNumber_r17;
	long	 segmentType_r17;
	OCTET_STRING_t	 segmentContainer_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SIB17_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_segmentType_r17_3;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SIB17_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_SIB17_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_SIB17_r17_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SIB17_r17_H_ */
#include <asn_internal.h>
