/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_SIB5_H_
#define	_SIB5_H_


#include <asn_application.h>

/* Including external dependencies */
#include "T-Reselection.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SIB5__ext2__idleModeMeasVoiceFallback_r17 {
	SIB5__ext2__idleModeMeasVoiceFallback_r17_true	= 0
} e_SIB5__ext2__idleModeMeasVoiceFallback_r17;

/* Forward declarations */
struct CarrierFreqListEUTRA;
struct SpeedStateScaleFactors;
struct CarrierFreqListEUTRA_v1610;
struct CarrierFreqListEUTRA_v1700;

/* SIB5 */
typedef struct SIB5 {
	struct CarrierFreqListEUTRA	*carrierFreqListEUTRA;	/* OPTIONAL */
	T_Reselection_t	 t_ReselectionEUTRA;
	struct SpeedStateScaleFactors	*t_ReselectionEUTRA_SF;	/* OPTIONAL */
	OCTET_STRING_t	*lateNonCriticalExtension;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct SIB5__ext1 {
		struct CarrierFreqListEUTRA_v1610	*carrierFreqListEUTRA_v1610;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	struct SIB5__ext2 {
		struct CarrierFreqListEUTRA_v1700	*carrierFreqListEUTRA_v1700;	/* OPTIONAL */
		long	*idleModeMeasVoiceFallback_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext2;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SIB5_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_idleModeMeasVoiceFallback_r17_11;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SIB5;
extern asn_SEQUENCE_specifics_t asn_SPC_SIB5_specs_1;
extern asn_TYPE_member_t asn_MBR_SIB5_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CarrierFreqListEUTRA.h"
#include "SpeedStateScaleFactors.h"
#include "CarrierFreqListEUTRA-v1610.h"
#include "CarrierFreqListEUTRA-v1700.h"

#endif	/* _SIB5_H_ */
#include <asn_internal.h>
