/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-Sidelink-Preconf"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_SidelinkPreconfigNR_r16_H_
#define	_SidelinkPreconfigNR_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <NativeEnumerated.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SidelinkPreconfigNR_r16__t400_r16 {
	SidelinkPreconfigNR_r16__t400_r16_ms100	= 0,
	SidelinkPreconfigNR_r16__t400_r16_ms200	= 1,
	SidelinkPreconfigNR_r16__t400_r16_ms300	= 2,
	SidelinkPreconfigNR_r16__t400_r16_ms400	= 3,
	SidelinkPreconfigNR_r16__t400_r16_ms600	= 4,
	SidelinkPreconfigNR_r16__t400_r16_ms1000	= 5,
	SidelinkPreconfigNR_r16__t400_r16_ms1500	= 6,
	SidelinkPreconfigNR_r16__t400_r16_ms2000	= 7
} e_SidelinkPreconfigNR_r16__t400_r16;
typedef enum SidelinkPreconfigNR_r16__sl_MaxNumConsecutiveDTX_r16 {
	SidelinkPreconfigNR_r16__sl_MaxNumConsecutiveDTX_r16_n1	= 0,
	SidelinkPreconfigNR_r16__sl_MaxNumConsecutiveDTX_r16_n2	= 1,
	SidelinkPreconfigNR_r16__sl_MaxNumConsecutiveDTX_r16_n3	= 2,
	SidelinkPreconfigNR_r16__sl_MaxNumConsecutiveDTX_r16_n4	= 3,
	SidelinkPreconfigNR_r16__sl_MaxNumConsecutiveDTX_r16_n6	= 4,
	SidelinkPreconfigNR_r16__sl_MaxNumConsecutiveDTX_r16_n8	= 5,
	SidelinkPreconfigNR_r16__sl_MaxNumConsecutiveDTX_r16_n16	= 6,
	SidelinkPreconfigNR_r16__sl_MaxNumConsecutiveDTX_r16_n32	= 7
} e_SidelinkPreconfigNR_r16__sl_MaxNumConsecutiveDTX_r16;
typedef enum SidelinkPreconfigNR_r16__sl_CSI_Acquisition_r16 {
	SidelinkPreconfigNR_r16__sl_CSI_Acquisition_r16_enabled	= 0
} e_SidelinkPreconfigNR_r16__sl_CSI_Acquisition_r16;

/* Forward declarations */
struct SL_NR_AnchorCarrierFreqList_r16;
struct SL_EUTRA_AnchorCarrierFreqList_r16;
struct SL_MeasConfigCommon_r16;
struct SL_PreconfigGeneral_r16;
struct SL_UE_SelectedConfig_r16;
struct SL_RoHC_Profiles_r16;
struct SL_FreqConfigCommon_r16;
struct SL_RadioBearerConfig_r16;
struct SL_RLC_BearerConfig_r16;
struct SL_DRX_ConfigGC_BC_r17;
struct SL_TxProfileList_r17;
struct SL_RemoteUE_Config_r17;

/* SidelinkPreconfigNR-r16 */
typedef struct SidelinkPreconfigNR_r16 {
	struct SidelinkPreconfigNR_r16__sl_PreconfigFreqInfoList_r16 {
		A_SEQUENCE_OF(struct SL_FreqConfigCommon_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sl_PreconfigFreqInfoList_r16;
	struct SL_NR_AnchorCarrierFreqList_r16	*sl_PreconfigNR_AnchorCarrierFreqList_r16;	/* OPTIONAL */
	struct SL_EUTRA_AnchorCarrierFreqList_r16	*sl_PreconfigEUTRA_AnchorCarrierFreqList_r16;	/* OPTIONAL */
	struct SidelinkPreconfigNR_r16__sl_RadioBearerPreConfigList_r16 {
		A_SEQUENCE_OF(struct SL_RadioBearerConfig_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sl_RadioBearerPreConfigList_r16;
	struct SidelinkPreconfigNR_r16__sl_RLC_BearerPreConfigList_r16 {
		A_SEQUENCE_OF(struct SL_RLC_BearerConfig_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sl_RLC_BearerPreConfigList_r16;
	struct SL_MeasConfigCommon_r16	*sl_MeasPreConfig_r16;	/* OPTIONAL */
	long	*sl_OffsetDFN_r16;	/* OPTIONAL */
	long	*t400_r16;	/* OPTIONAL */
	long	*sl_MaxNumConsecutiveDTX_r16;	/* OPTIONAL */
	long	*sl_SSB_PriorityNR_r16;	/* OPTIONAL */
	struct SL_PreconfigGeneral_r16	*sl_PreconfigGeneral_r16;	/* OPTIONAL */
	struct SL_UE_SelectedConfig_r16	*sl_UE_SelectedPreConfig_r16;	/* OPTIONAL */
	long	*sl_CSI_Acquisition_r16;	/* OPTIONAL */
	struct SL_RoHC_Profiles_r16	*sl_RoHC_Profiles_r16;	/* OPTIONAL */
	long	*sl_MaxCID_r16;	/* DEFAULT 15 */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct SidelinkPreconfigNR_r16__ext1 {
		struct SL_DRX_ConfigGC_BC_r17	*sl_DRX_PreConfigGC_BC_r17;	/* OPTIONAL */
		struct SL_TxProfileList_r17	*sl_TxProfileList_r17;	/* OPTIONAL */
		struct SL_RemoteUE_Config_r17	*sl_PreconfigDiscConfig_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SidelinkPreconfigNR_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_t400_r16_12;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_sl_MaxNumConsecutiveDTX_r16_21;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_sl_CSI_Acquisition_r16_33;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SidelinkPreconfigNR_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_SidelinkPreconfigNR_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_SidelinkPreconfigNR_r16_1[16];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SL-NR-AnchorCarrierFreqList-r16.h"
#include "SL-EUTRA-AnchorCarrierFreqList-r16.h"
#include "SL-MeasConfigCommon-r16.h"
#include "SL-PreconfigGeneral-r16.h"
#include "SL-UE-SelectedConfig-r16.h"
#include "SL-RoHC-Profiles-r16.h"
#include "SL-FreqConfigCommon-r16.h"
#include "SL-RadioBearerConfig-r16.h"
#include "SL-RLC-BearerConfig-r16.h"
#include "SL-DRX-ConfigGC-BC-r17.h"
#include "SL-TxProfileList-r17.h"
#include "SL-RemoteUE-Config-r17.h"

#endif	/* _SidelinkPreconfigNR_r16_H_ */
#include <asn_internal.h>
