/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_SL_DRX_GC_BC_QoS_r17_H_
#define	_SL_DRX_GC_BC_QoS_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17_PR {
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17_PR_NOTHING,	/* No components present */
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17_PR_subMilliSeconds,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17_PR_milliSeconds
} SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17_PR;
typedef enum SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds {
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms1	= 0,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms2	= 1,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms3	= 2,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms4	= 3,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms5	= 4,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms6	= 5,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms8	= 6,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms10	= 7,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms20	= 8,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms30	= 9,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms40	= 10,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms50	= 11,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms60	= 12,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms80	= 13,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms100	= 14,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms200	= 15,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms300	= 16,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms400	= 17,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms500	= 18,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms600	= 19,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms800	= 20,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms1000	= 21,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms1200	= 22,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_ms1600	= 23,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_spare8	= 24,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_spare7	= 25,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_spare6	= 26,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_spare5	= 27,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_spare4	= 28,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_spare3	= 29,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_spare2	= 30,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds_spare1	= 31
} e_SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17__milliSeconds;
typedef enum SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17 {
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms0	= 0,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms1	= 1,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms2	= 2,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms3	= 3,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms4	= 4,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms5	= 5,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms6	= 6,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms8	= 7,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms10	= 8,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms20	= 9,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms30	= 10,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms40	= 11,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms50	= 12,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms60	= 13,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms80	= 14,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms100	= 15,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms200	= 16,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms300	= 17,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms500	= 18,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms750	= 19,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms1280	= 20,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms1920	= 21,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_ms2560	= 22,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_spare9	= 23,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_spare8	= 24,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_spare7	= 25,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_spare6	= 26,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_spare5	= 27,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_spare4	= 28,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_spare3	= 29,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_spare2	= 30,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17_spare1	= 31
} e_SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_InactivityTimer_r17;
typedef enum SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17 {
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms10	= 0,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms20	= 1,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms32	= 2,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms40	= 3,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms60	= 4,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms64	= 5,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms70	= 6,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms80	= 7,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms128	= 8,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms160	= 9,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms256	= 10,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms320	= 11,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms512	= 12,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms640	= 13,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms1024	= 14,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms1280	= 15,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms2048	= 16,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms2560	= 17,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms5120	= 18,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_ms10240	= 19,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_spare12	= 20,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_spare11	= 21,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_spare10	= 22,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_spare9	= 23,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_spare8	= 24,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_spare7	= 25,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_spare6	= 26,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_spare5	= 27,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_spare4	= 28,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_spare3	= 29,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_spare2	= 30,
	SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17_spare1	= 31
} e_SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_Cycle_r17;

/* Forward declarations */
struct SL_QoS_Profile_r16;

/* SL-DRX-GC-BC-QoS-r17 */
typedef struct SL_DRX_GC_BC_QoS_r17 {
	struct SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_MappedQoS_FlowList_r17 {
		A_SEQUENCE_OF(struct SL_QoS_Profile_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sl_DRX_GC_BC_MappedQoS_FlowList_r17;
	struct SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17 {
		SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17_PR present;
		union SL_DRX_GC_BC_QoS_r17__sl_DRX_GC_BC_OnDurationTimer_r17_u {
			long	 subMilliSeconds;
			long	 milliSeconds;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} sl_DRX_GC_BC_OnDurationTimer_r17;
	long	 sl_DRX_GC_InactivityTimer_r17;
	long	 sl_DRX_GC_BC_Cycle_r17;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_DRX_GC_BC_QoS_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_milliSeconds_6;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_sl_DRX_GC_InactivityTimer_r17_39;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_sl_DRX_GC_BC_Cycle_r17_72;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SL_DRX_GC_BC_QoS_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_SL_DRX_GC_BC_QoS_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_SL_DRX_GC_BC_QoS_r17_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SL-QoS-Profile-r16.h"

#endif	/* _SL_DRX_GC_BC_QoS_r17_H_ */
#include <asn_internal.h>
