/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_SL_SIB_ReqInfo_r17_H_
#define	_SL_SIB_ReqInfo_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SL_SIB_ReqInfo_r17 {
	SL_SIB_ReqInfo_r17_sib1	= 0,
	SL_SIB_ReqInfo_r17_sib2	= 1,
	SL_SIB_ReqInfo_r17_sib3	= 2,
	SL_SIB_ReqInfo_r17_sib4	= 3,
	SL_SIB_ReqInfo_r17_sib5	= 4,
	SL_SIB_ReqInfo_r17_sib6	= 5,
	SL_SIB_ReqInfo_r17_sib7	= 6,
	SL_SIB_ReqInfo_r17_sib8	= 7,
	SL_SIB_ReqInfo_r17_sib9	= 8,
	SL_SIB_ReqInfo_r17_sib10	= 9,
	SL_SIB_ReqInfo_r17_sib11	= 10,
	SL_SIB_ReqInfo_r17_sib12	= 11,
	SL_SIB_ReqInfo_r17_sib13	= 12,
	SL_SIB_ReqInfo_r17_sib14	= 13,
	SL_SIB_ReqInfo_r17_sib15	= 14,
	SL_SIB_ReqInfo_r17_sib16	= 15,
	SL_SIB_ReqInfo_r17_sib17	= 16,
	SL_SIB_ReqInfo_r17_sib18	= 17,
	SL_SIB_ReqInfo_r17_sib19	= 18,
	SL_SIB_ReqInfo_r17_sib20	= 19,
	SL_SIB_ReqInfo_r17_sib21	= 20,
	SL_SIB_ReqInfo_r17_spare11	= 21,
	SL_SIB_ReqInfo_r17_spare10	= 22,
	SL_SIB_ReqInfo_r17_spare9	= 23,
	SL_SIB_ReqInfo_r17_spare8	= 24,
	SL_SIB_ReqInfo_r17_spare7	= 25,
	SL_SIB_ReqInfo_r17_spare6	= 26,
	SL_SIB_ReqInfo_r17_spare5	= 27,
	SL_SIB_ReqInfo_r17_spare4	= 28,
	SL_SIB_ReqInfo_r17_spare3	= 29,
	SL_SIB_ReqInfo_r17_spare2	= 30,
	SL_SIB_ReqInfo_r17_spare1	= 31
	/*
	 * Enumeration is extensible
	 */
} e_SL_SIB_ReqInfo_r17;

/* SL-SIB-ReqInfo-r17 */
typedef long	 SL_SIB_ReqInfo_r17_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SL_SIB_ReqInfo_r17_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SL_SIB_ReqInfo_r17;
extern const asn_INTEGER_specifics_t asn_SPC_SL_SIB_ReqInfo_r17_specs_1;
asn_struct_free_f SL_SIB_ReqInfo_r17_free;
asn_struct_print_f SL_SIB_ReqInfo_r17_print;
asn_constr_check_f SL_SIB_ReqInfo_r17_constraint;
xer_type_decoder_f SL_SIB_ReqInfo_r17_decode_xer;
xer_type_encoder_f SL_SIB_ReqInfo_r17_encode_xer;
per_type_decoder_f SL_SIB_ReqInfo_r17_decode_uper;
per_type_encoder_f SL_SIB_ReqInfo_r17_encode_uper;
per_type_decoder_f SL_SIB_ReqInfo_r17_decode_aper;
per_type_encoder_f SL_SIB_ReqInfo_r17_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SL_SIB_ReqInfo_r17_H_ */
#include <asn_internal.h>
