/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_SL_SyncAllowed_r16_H_
#define	_SL_SyncAllowed_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SL_SyncAllowed_r16__gnss_Sync_r16 {
	SL_SyncAllowed_r16__gnss_Sync_r16_true	= 0
} e_SL_SyncAllowed_r16__gnss_Sync_r16;
typedef enum SL_SyncAllowed_r16__gnbEnb_Sync_r16 {
	SL_SyncAllowed_r16__gnbEnb_Sync_r16_true	= 0
} e_SL_SyncAllowed_r16__gnbEnb_Sync_r16;
typedef enum SL_SyncAllowed_r16__ue_Sync_r16 {
	SL_SyncAllowed_r16__ue_Sync_r16_true	= 0
} e_SL_SyncAllowed_r16__ue_Sync_r16;

/* SL-SyncAllowed-r16 */
typedef struct SL_SyncAllowed_r16 {
	long	*gnss_Sync_r16;	/* OPTIONAL */
	long	*gnbEnb_Sync_r16;	/* OPTIONAL */
	long	*ue_Sync_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_SyncAllowed_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_gnss_Sync_r16_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_gnbEnb_Sync_r16_4;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ue_Sync_r16_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SL_SyncAllowed_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_SL_SyncAllowed_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_SL_SyncAllowed_r16_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SL_SyncAllowed_r16_H_ */
#include <asn_internal.h>
