/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_SL_ServingCellInfo_r17_H_
#define	_SL_ServingCellInfo_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PhysCellId.h"
#include "ARFCN-ValueNR.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SL-ServingCellInfo-r17 */
typedef struct SL_ServingCellInfo_r17 {
	PhysCellId_t	 sl_PhysCellId_r17;
	ARFCN_ValueNR_t	 sl_CarrierFreqNR_r17;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SL_ServingCellInfo_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SL_ServingCellInfo_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_SL_ServingCellInfo_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_SL_ServingCellInfo_r17_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SL_ServingCellInfo_r17_H_ */
#include <asn_internal.h>
