/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_SLRB_Config_r16_H_
#define	_SLRB_Config_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SLRB-PC5-ConfigIndex-r16.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SL_SDAP_ConfigPC5_r16;
struct SL_PDCP_ConfigPC5_r16;
struct SL_RLC_ConfigPC5_r16;
struct SL_LogicalChannelConfigPC5_r16;

/* SLRB-Config-r16 */
typedef struct SLRB_Config_r16 {
	SLRB_PC5_ConfigIndex_r16_t	 slrb_PC5_ConfigIndex_r16;
	struct SL_SDAP_ConfigPC5_r16	*sl_SDAP_ConfigPC5_r16;	/* OPTIONAL */
	struct SL_PDCP_ConfigPC5_r16	*sl_PDCP_ConfigPC5_r16;	/* OPTIONAL */
	struct SL_RLC_ConfigPC5_r16	*sl_RLC_ConfigPC5_r16;	/* OPTIONAL */
	struct SL_LogicalChannelConfigPC5_r16	*sl_MAC_LogicalChannelConfigPC5_r16;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SLRB_Config_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SLRB_Config_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_SLRB_Config_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_SLRB_Config_r16_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SL-SDAP-ConfigPC5-r16.h"
#include "SL-PDCP-ConfigPC5-r16.h"
#include "SL-RLC-ConfigPC5-r16.h"
#include "SL-LogicalChannelConfigPC5-r16.h"

#endif	/* _SLRB_Config_r16_H_ */
#include <asn_internal.h>
