/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_SpatialRelationInfo_PDC_r17_H_
#define	_SpatialRelationInfo_PDC_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SSB-Index.h"
#include "NZP-CSI-RS-ResourceId.h"
#include "NR-DL-PRS-ResourceID-r17.h"
#include "SRS-ResourceId.h"
#include "BWP-Id.h"
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SpatialRelationInfo_PDC_r17__referenceSignal_PR {
	SpatialRelationInfo_PDC_r17__referenceSignal_PR_NOTHING,	/* No components present */
	SpatialRelationInfo_PDC_r17__referenceSignal_PR_ssb_Index,
	SpatialRelationInfo_PDC_r17__referenceSignal_PR_csi_RS_Index,
	SpatialRelationInfo_PDC_r17__referenceSignal_PR_dl_PRS_PDC,
	SpatialRelationInfo_PDC_r17__referenceSignal_PR_srs
	/* Extensions may appear below */
	
} SpatialRelationInfo_PDC_r17__referenceSignal_PR;

/* SpatialRelationInfo-PDC-r17 */
typedef struct SpatialRelationInfo_PDC_r17 {
	struct SpatialRelationInfo_PDC_r17__referenceSignal {
		SpatialRelationInfo_PDC_r17__referenceSignal_PR present;
		union SpatialRelationInfo_PDC_r17__referenceSignal_u {
			SSB_Index_t	 ssb_Index;
			NZP_CSI_RS_ResourceId_t	 csi_RS_Index;
			NR_DL_PRS_ResourceID_r17_t	 dl_PRS_PDC;
			struct SpatialRelationInfo_PDC_r17__referenceSignal__srs {
				SRS_ResourceId_t	 resourceId;
				BWP_Id_t	 uplinkBWP;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *srs;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} referenceSignal;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SpatialRelationInfo_PDC_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpatialRelationInfo_PDC_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_SpatialRelationInfo_PDC_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_SpatialRelationInfo_PDC_r17_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _SpatialRelationInfo_PDC_r17_H_ */
#include <asn_internal.h>
