/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_SpCellConfig_H_
#define	_SpCellConfig_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ServCellIndex.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SpCellConfig__rlmInSyncOutOfSyncThreshold {
	SpCellConfig__rlmInSyncOutOfSyncThreshold_n1	= 0
} e_SpCellConfig__rlmInSyncOutOfSyncThreshold;
typedef enum SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__s_SearchDeltaP_Connected_r17 {
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__s_SearchDeltaP_Connected_r17_dB3	= 0,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__s_SearchDeltaP_Connected_r17_dB6	= 1,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__s_SearchDeltaP_Connected_r17_dB9	= 2,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__s_SearchDeltaP_Connected_r17_dB12	= 3,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__s_SearchDeltaP_Connected_r17_dB15	= 4,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__s_SearchDeltaP_Connected_r17_spare3	= 5,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__s_SearchDeltaP_Connected_r17_spare2	= 6,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__s_SearchDeltaP_Connected_r17_spare1	= 7
} e_SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__s_SearchDeltaP_Connected_r17;
typedef enum SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17 {
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_s5	= 0,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_s10	= 1,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_s20	= 2,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_s30	= 3,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_s60	= 4,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_s120	= 5,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_s180	= 6,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_s240	= 7,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_s300	= 8,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_spare7	= 9,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_spare6	= 10,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_spare5	= 11,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_spare4	= 12,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_spare3	= 13,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_spare2	= 14,
	SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17_spare1	= 15
} e_SpCellConfig__ext1__lowMobilityEvaluationConnected_r17__t_SearchDeltaP_Connected_r17;

/* Forward declarations */
struct ReconfigurationWithSync;
struct SetupRelease_RLF_TimersAndConstants;
struct ServingCellConfig;
struct GoodServingCellEvaluation_r17;
struct SetupRelease_DeactivatedSCG_Config_r17;

/* SpCellConfig */
typedef struct SpCellConfig {
	ServCellIndex_t	*servCellIndex;	/* OPTIONAL */
	struct ReconfigurationWithSync	*reconfigurationWithSync;	/* OPTIONAL */
	struct SetupRelease_RLF_TimersAndConstants	*rlf_TimersAndConstants;	/* OPTIONAL */
	long	*rlmInSyncOutOfSyncThreshold;	/* OPTIONAL */
	struct ServingCellConfig	*spCellConfigDedicated;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct SpCellConfig__ext1 {
		struct SpCellConfig__ext1__lowMobilityEvaluationConnected_r17 {
			long	 s_SearchDeltaP_Connected_r17;
			long	 t_SearchDeltaP_Connected_r17;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *lowMobilityEvaluationConnected_r17;
		struct GoodServingCellEvaluation_r17	*goodServingCellEvaluationRLM_r17;	/* OPTIONAL */
		struct GoodServingCellEvaluation_r17	*goodServingCellEvaluationBFD_r17;	/* OPTIONAL */
		struct SetupRelease_DeactivatedSCG_Config_r17	*deactivatedSCG_Config_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SpCellConfig_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_rlmInSyncOutOfSyncThreshold_5;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_s_SearchDeltaP_Connected_r17_11;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_t_SearchDeltaP_Connected_r17_20;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SpCellConfig;
extern asn_SEQUENCE_specifics_t asn_SPC_SpCellConfig_specs_1;
extern asn_TYPE_member_t asn_MBR_SpCellConfig_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ReconfigurationWithSync.h"
#include "SetupRelease.h"
#include "ServingCellConfig.h"
#include "GoodServingCellEvaluation-r17.h"

#endif	/* _SpCellConfig_H_ */
#include <asn_internal.h>
