/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_SRS_PosRRC_InactiveConfig_r17_H_
#define	_SRS_PosRRC_InactiveConfig_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeAlignmentTimer.h"
#include "RSRP-ChangeThreshold-r17.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SRS_PosConfig_r17;
struct BWP;

/* SRS-PosRRC-InactiveConfig-r17 */
typedef struct SRS_PosRRC_InactiveConfig_r17 {
	struct SRS_PosConfig_r17	*srs_PosConfigNUL_r17;	/* OPTIONAL */
	struct SRS_PosConfig_r17	*srs_PosConfigSUL_r17;	/* OPTIONAL */
	struct BWP	*bwp_NUL_r17;	/* OPTIONAL */
	struct BWP	*bwp_SUL_r17;	/* OPTIONAL */
	TimeAlignmentTimer_t	*inactivePosSRS_TimeAlignmentTimer_r17;	/* OPTIONAL */
	RSRP_ChangeThreshold_r17_t	*inactivePosSRS_RSRP_ChangeThreshold_r17;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SRS_PosRRC_InactiveConfig_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SRS_PosRRC_InactiveConfig_r17;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "SRS-PosConfig-r17.h"
#include "BWP.h"

#endif	/* _SRS_PosRRC_InactiveConfig_r17_H_ */
#include <asn_internal.h>
