/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_SupportedBandwidth_v1700_H_
#define	_SupportedBandwidth_v1700_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SupportedBandwidth_v1700_PR {
	SupportedBandwidth_v1700_PR_NOTHING,	/* No components present */
	SupportedBandwidth_v1700_PR_fr1_r17,
	SupportedBandwidth_v1700_PR_fr2_r17
} SupportedBandwidth_v1700_PR;
typedef enum SupportedBandwidth_v1700__fr1_r17 {
	SupportedBandwidth_v1700__fr1_r17_mhz5	= 0,
	SupportedBandwidth_v1700__fr1_r17_mhz10	= 1,
	SupportedBandwidth_v1700__fr1_r17_mhz15	= 2,
	SupportedBandwidth_v1700__fr1_r17_mhz20	= 3,
	SupportedBandwidth_v1700__fr1_r17_mhz25	= 4,
	SupportedBandwidth_v1700__fr1_r17_mhz30	= 5,
	SupportedBandwidth_v1700__fr1_r17_mhz35	= 6,
	SupportedBandwidth_v1700__fr1_r17_mhz40	= 7,
	SupportedBandwidth_v1700__fr1_r17_mhz45	= 8,
	SupportedBandwidth_v1700__fr1_r17_mhz50	= 9,
	SupportedBandwidth_v1700__fr1_r17_mhz60	= 10,
	SupportedBandwidth_v1700__fr1_r17_mhz70	= 11,
	SupportedBandwidth_v1700__fr1_r17_mhz80	= 12,
	SupportedBandwidth_v1700__fr1_r17_mhz90	= 13,
	SupportedBandwidth_v1700__fr1_r17_mhz100	= 14
} e_SupportedBandwidth_v1700__fr1_r17;
typedef enum SupportedBandwidth_v1700__fr2_r17 {
	SupportedBandwidth_v1700__fr2_r17_mhz50	= 0,
	SupportedBandwidth_v1700__fr2_r17_mhz100	= 1,
	SupportedBandwidth_v1700__fr2_r17_mhz200	= 2,
	SupportedBandwidth_v1700__fr2_r17_mhz400	= 3,
	SupportedBandwidth_v1700__fr2_r17_mhz800	= 4,
	SupportedBandwidth_v1700__fr2_r17_mhz1600	= 5,
	SupportedBandwidth_v1700__fr2_r17_mhz2000	= 6
} e_SupportedBandwidth_v1700__fr2_r17;

/* SupportedBandwidth-v1700 */
typedef struct SupportedBandwidth_v1700 {
	SupportedBandwidth_v1700_PR present;
	union SupportedBandwidth_v1700_u {
		long	 fr1_r17;
		long	 fr2_r17;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SupportedBandwidth_v1700_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_fr1_r17_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_fr2_r17_18;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_SupportedBandwidth_v1700;
extern asn_CHOICE_specifics_t asn_SPC_SupportedBandwidth_v1700_specs_1;
extern asn_TYPE_member_t asn_MBR_SupportedBandwidth_v1700_1[2];
extern asn_per_constraints_t asn_PER_type_SupportedBandwidth_v1700_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _SupportedBandwidth_v1700_H_ */
#include <asn_internal.h>
