/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_UE_NR_Capability_v1700_H_
#define	_UE_NR_Capability_v1700_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "MeasAndMobParameters-v1700.h"
#include "MBS-Parameters-r17.h"
#include <BIT_STRING.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UE_NR_Capability_v1700__inactiveStatePO_Determination_r17 {
	UE_NR_Capability_v1700__inactiveStatePO_Determination_r17_supported	= 0
} e_UE_NR_Capability_v1700__inactiveStatePO_Determination_r17;
typedef enum UE_NR_Capability_v1700__ra_SDT_r17 {
	UE_NR_Capability_v1700__ra_SDT_r17_supported	= 0
} e_UE_NR_Capability_v1700__ra_SDT_r17;
typedef enum UE_NR_Capability_v1700__srb_SDT_r17 {
	UE_NR_Capability_v1700__srb_SDT_r17_supported	= 0
} e_UE_NR_Capability_v1700__srb_SDT_r17;
typedef enum UE_NR_Capability_v1700__gNB_SideRTT_BasedPDC_r17 {
	UE_NR_Capability_v1700__gNB_SideRTT_BasedPDC_r17_supported	= 0
} e_UE_NR_Capability_v1700__gNB_SideRTT_BasedPDC_r17;
typedef enum UE_NR_Capability_v1700__bh_RLF_DetectionRecovery_Indication_r17 {
	UE_NR_Capability_v1700__bh_RLF_DetectionRecovery_Indication_r17_supported	= 0
} e_UE_NR_Capability_v1700__bh_RLF_DetectionRecovery_Indication_r17;
typedef enum UE_NR_Capability_v1700__musim_GapPreference_r17 {
	UE_NR_Capability_v1700__musim_GapPreference_r17_supported	= 0
} e_UE_NR_Capability_v1700__musim_GapPreference_r17;
typedef enum UE_NR_Capability_v1700__musimLeaveConnected_r17 {
	UE_NR_Capability_v1700__musimLeaveConnected_r17_supported	= 0
} e_UE_NR_Capability_v1700__musimLeaveConnected_r17;
typedef enum UE_NR_Capability_v1700__nonTerrestrialNetwork_r17 {
	UE_NR_Capability_v1700__nonTerrestrialNetwork_r17_supported	= 0
} e_UE_NR_Capability_v1700__nonTerrestrialNetwork_r17;
typedef enum UE_NR_Capability_v1700__ntn_ScenarioSupport_r17 {
	UE_NR_Capability_v1700__ntn_ScenarioSupport_r17_gso	= 0,
	UE_NR_Capability_v1700__ntn_ScenarioSupport_r17_ngso	= 1
} e_UE_NR_Capability_v1700__ntn_ScenarioSupport_r17;
typedef enum UE_NR_Capability_v1700__sliceInfoforCellReselection_r17 {
	UE_NR_Capability_v1700__sliceInfoforCellReselection_r17_supported	= 0
} e_UE_NR_Capability_v1700__sliceInfoforCellReselection_r17;

/* Forward declarations */
struct HighSpeedParameters_v1700;
struct PowSav_Parameters_v1700;
struct MAC_Parameters_v1700;
struct IMS_Parameters_v1700;
struct AppLayerMeasParameters_r17;
struct RedCapParameters_r17;
struct NRDC_Parameters_v1700;
struct BAP_Parameters_v1700;
struct UE_RadioPagingInfo_r17;
struct NTN_Parameters_r17;

/* UE-NR-Capability-v1700 */
typedef struct UE_NR_Capability_v1700 {
	long	*inactiveStatePO_Determination_r17;	/* OPTIONAL */
	struct HighSpeedParameters_v1700	*highSpeedParameters_v1700;	/* OPTIONAL */
	struct PowSav_Parameters_v1700	*powSav_Parameters_v1700;	/* OPTIONAL */
	struct MAC_Parameters_v1700	*mac_Parameters_v1700;	/* OPTIONAL */
	struct IMS_Parameters_v1700	*ims_Parameters_v1700;	/* OPTIONAL */
	MeasAndMobParameters_v1700_t	 measAndMobParameters_v1700;
	struct AppLayerMeasParameters_r17	*appLayerMeasParameters_r17;	/* OPTIONAL */
	struct RedCapParameters_r17	*redCapParameters_r17;	/* OPTIONAL */
	long	*ra_SDT_r17;	/* OPTIONAL */
	long	*srb_SDT_r17;	/* OPTIONAL */
	long	*gNB_SideRTT_BasedPDC_r17;	/* OPTIONAL */
	long	*bh_RLF_DetectionRecovery_Indication_r17;	/* OPTIONAL */
	struct NRDC_Parameters_v1700	*nrdc_Parameters_v1700;	/* OPTIONAL */
	struct BAP_Parameters_v1700	*bap_Parameters_v1700;	/* OPTIONAL */
	long	*musim_GapPreference_r17;	/* OPTIONAL */
	long	*musimLeaveConnected_r17;	/* OPTIONAL */
	MBS_Parameters_r17_t	 mbs_Parameters_r17;
	long	*nonTerrestrialNetwork_r17;	/* OPTIONAL */
	long	*ntn_ScenarioSupport_r17;	/* OPTIONAL */
	long	*sliceInfoforCellReselection_r17;	/* OPTIONAL */
	struct UE_RadioPagingInfo_r17	*ue_RadioPagingInfo_r17;	/* OPTIONAL */
	BIT_STRING_t	*ul_GapFR2_Pattern_r17;	/* OPTIONAL */
	struct NTN_Parameters_r17	*ntn_Parameters_r17;	/* OPTIONAL */
	struct UE_NR_Capability_v1700__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_NR_Capability_v1700_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_inactiveStatePO_Determination_r17_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ra_SDT_r17_11;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_srb_SDT_r17_13;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_gNB_SideRTT_BasedPDC_r17_15;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_bh_RLF_DetectionRecovery_Indication_r17_17;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_musim_GapPreference_r17_21;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_musimLeaveConnected_r17_23;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_nonTerrestrialNetwork_r17_26;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_ntn_ScenarioSupport_r17_28;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_sliceInfoforCellReselection_r17_31;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UE_NR_Capability_v1700;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_NR_Capability_v1700_specs_1;
extern asn_TYPE_member_t asn_MBR_UE_NR_Capability_v1700_1[24];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "HighSpeedParameters-v1700.h"
#include "PowSav-Parameters-v1700.h"
#include "MAC-Parameters-v1700.h"
#include "IMS-Parameters-v1700.h"
#include "AppLayerMeasParameters-r17.h"
#include "RedCapParameters-r17.h"
#include "NRDC-Parameters-v1700.h"
#include "BAP-Parameters-v1700.h"
#include "UE-RadioPagingInfo-r17.h"
#include "NTN-Parameters-r17.h"

#endif	/* _UE_NR_Capability_v1700_H_ */
#include <asn_internal.h>
