/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_UEAssistanceInformation_v1700_IEs_H_
#define	_UEAssistanceInformation_v1700_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BOOLEAN.h>
#include <BIT_STRING.h>
#include <NativeEnumerated.h>
#include "ResumeCause.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UEAssistanceInformation_v1700_IEs__scg_DeactivationPreference_r17 {
	UEAssistanceInformation_v1700_IEs__scg_DeactivationPreference_r17_scgDeactivationPreferred	= 0,
	UEAssistanceInformation_v1700_IEs__scg_DeactivationPreference_r17_noPreference	= 1
} e_UEAssistanceInformation_v1700_IEs__scg_DeactivationPreference_r17;
typedef enum UEAssistanceInformation_v1700_IEs__uplinkData_r17 {
	UEAssistanceInformation_v1700_IEs__uplinkData_r17_true	= 0
} e_UEAssistanceInformation_v1700_IEs__uplinkData_r17;

/* Forward declarations */
struct UL_GapFR2_Preference_r17;
struct MUSIM_Assistance_r17;
struct OverheatingAssistance_r17;
struct MaxBW_PreferenceFR2_2_r17;
struct MaxMIMO_LayerPreferenceFR2_2_r17;
struct MinSchedulingOffsetPreferenceExt_r17;
struct PropagationDelayDifference_r17;

/* UEAssistanceInformation-v1700-IEs */
typedef struct UEAssistanceInformation_v1700_IEs {
	struct UL_GapFR2_Preference_r17	*ul_GapFR2_Preference_r17;	/* OPTIONAL */
	struct MUSIM_Assistance_r17	*musim_Assistance_r17;	/* OPTIONAL */
	struct OverheatingAssistance_r17	*overheatingAssistance_r17;	/* OPTIONAL */
	struct MaxBW_PreferenceFR2_2_r17	*maxBW_PreferenceFR2_2_r17;	/* OPTIONAL */
	struct MaxMIMO_LayerPreferenceFR2_2_r17	*maxMIMO_LayerPreferenceFR2_2_r17;	/* OPTIONAL */
	struct MinSchedulingOffsetPreferenceExt_r17	*minSchedulingOffsetPreferenceExt_r17;	/* OPTIONAL */
	BOOLEAN_t	*rlm_MeasRelaxationState_r17;	/* OPTIONAL */
	BIT_STRING_t	*bfd_MeasRelaxationState_r17;	/* OPTIONAL */
	struct UEAssistanceInformation_v1700_IEs__nonSDT_DataIndication_r17 {
		ResumeCause_t	*resumeCause_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonSDT_DataIndication_r17;
	long	*scg_DeactivationPreference_r17;	/* OPTIONAL */
	long	*uplinkData_r17;	/* OPTIONAL */
	BOOLEAN_t	*rrm_MeasRelaxationFulfilment_r17;	/* OPTIONAL */
	struct PropagationDelayDifference_r17	*propagationDelayDifference_r17;	/* OPTIONAL */
	struct UEAssistanceInformation_v1700_IEs__nonCriticalExtension {
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *nonCriticalExtension;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UEAssistanceInformation_v1700_IEs_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_scg_DeactivationPreference_r17_12;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_uplinkData_r17_15;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UEAssistanceInformation_v1700_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UEAssistanceInformation_v1700_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UEAssistanceInformation_v1700_IEs_1[14];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "UL-GapFR2-Preference-r17.h"
#include "MUSIM-Assistance-r17.h"
#include "OverheatingAssistance-r17.h"
#include "MaxBW-PreferenceFR2-2-r17.h"
#include "MaxMIMO-LayerPreferenceFR2-2-r17.h"
#include "MinSchedulingOffsetPreferenceExt-r17.h"
#include "PropagationDelayDifference-r17.h"

#endif	/* _UEAssistanceInformation_v1700_IEs_H_ */
#include <asn_internal.h>
