/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PC5-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_UECapabilityInformationSidelink_r16_IEs_H_
#define	_UECapabilityInformationSidelink_r16_IEs_H_


#include <asn_application.h>

/* Including external dependencies */
#include "AccessStratumReleaseSidelink-r16.h"
#include <OCTET_STRING.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PDCP_ParametersSidelink_r16;
struct RLC_ParametersSidelink_r16;
struct BandCombinationListSidelinkNR_r16;
struct FreqBandList;
struct UECapabilityInformationSidelink_v1700_IEs;
struct BandSidelinkPC5_r16;

/* UECapabilityInformationSidelink-r16-IEs */
typedef struct UECapabilityInformationSidelink_r16_IEs {
	AccessStratumReleaseSidelink_r16_t	 accessStratumReleaseSidelink_r16;
	struct PDCP_ParametersSidelink_r16	*pdcp_ParametersSidelink_r16;	/* OPTIONAL */
	struct RLC_ParametersSidelink_r16	*rlc_ParametersSidelink_r16;	/* OPTIONAL */
	struct BandCombinationListSidelinkNR_r16	*supportedBandCombinationListSidelinkNR_r16;	/* OPTIONAL */
	struct UECapabilityInformationSidelink_r16_IEs__supportedBandListSidelink_r16 {
		A_SEQUENCE_OF(struct BandSidelinkPC5_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *supportedBandListSidelink_r16;
	struct FreqBandList	*appliedFreqBandListFilter_r16;	/* OPTIONAL */
	OCTET_STRING_t	*lateNonCriticalExtension;	/* OPTIONAL */
	struct UECapabilityInformationSidelink_v1700_IEs	*nonCriticalExtension;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UECapabilityInformationSidelink_r16_IEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UECapabilityInformationSidelink_r16_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UECapabilityInformationSidelink_r16_IEs_specs_1;
extern asn_TYPE_member_t asn_MBR_UECapabilityInformationSidelink_r16_IEs_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PDCP-ParametersSidelink-r16.h"
#include "RLC-ParametersSidelink-r16.h"
#include "BandCombinationListSidelinkNR-r16.h"
#include "FreqBandList.h"
#include "UECapabilityInformationSidelink-v1700-IEs.h"
#include "BandSidelinkPC5-r16.h"

#endif	/* _UECapabilityInformationSidelink_r16_IEs_H_ */
#include <asn_internal.h>
