/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_UplinkDataCompression_r17_H_
#define	_UplinkDataCompression_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NULL.h>
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UplinkDataCompression_r17_PR {
	UplinkDataCompression_r17_PR_NOTHING,	/* No components present */
	UplinkDataCompression_r17_PR_newSetup,
	UplinkDataCompression_r17_PR_drb_ContinueUDC
} UplinkDataCompression_r17_PR;
typedef enum UplinkDataCompression_r17__newSetup__bufferSize_r17 {
	UplinkDataCompression_r17__newSetup__bufferSize_r17_kbyte2	= 0,
	UplinkDataCompression_r17__newSetup__bufferSize_r17_kbyte4	= 1,
	UplinkDataCompression_r17__newSetup__bufferSize_r17_kbyte8	= 2,
	UplinkDataCompression_r17__newSetup__bufferSize_r17_spare1	= 3
} e_UplinkDataCompression_r17__newSetup__bufferSize_r17;
typedef enum UplinkDataCompression_r17__newSetup__dictionary_r17 {
	UplinkDataCompression_r17__newSetup__dictionary_r17_sip_SDP	= 0,
	UplinkDataCompression_r17__newSetup__dictionary_r17_operator	= 1
} e_UplinkDataCompression_r17__newSetup__dictionary_r17;

/* UplinkDataCompression-r17 */
typedef struct UplinkDataCompression_r17 {
	UplinkDataCompression_r17_PR present;
	union UplinkDataCompression_r17_u {
		struct UplinkDataCompression_r17__newSetup {
			long	 bufferSize_r17;
			long	*dictionary_r17;	/* OPTIONAL */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} *newSetup;
		NULL_t	 drb_ContinueUDC;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UplinkDataCompression_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_bufferSize_r17_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_dictionary_r17_8;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_UplinkDataCompression_r17;
extern asn_CHOICE_specifics_t asn_SPC_UplinkDataCompression_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_UplinkDataCompression_r17_1[2];
extern asn_per_constraints_t asn_PER_type_UplinkDataCompression_r17_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _UplinkDataCompression_r17_H_ */
#include <asn_internal.h>
