/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_Uu_RelayRLC_ChannelConfig_r17_H_
#define	_Uu_RelayRLC_ChannelConfig_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include "LogicalChannelIdentity.h"
#include "Uu-RelayRLC-ChannelID-r17.h"
#include <NativeEnumerated.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Uu_RelayRLC_ChannelConfig_r17__reestablishRLC_r17 {
	Uu_RelayRLC_ChannelConfig_r17__reestablishRLC_r17_true	= 0
} e_Uu_RelayRLC_ChannelConfig_r17__reestablishRLC_r17;

/* Forward declarations */
struct RLC_Config;
struct LogicalChannelConfig;

/* Uu-RelayRLC-ChannelConfig-r17 */
typedef struct Uu_RelayRLC_ChannelConfig_r17 {
	LogicalChannelIdentity_t	*uu_LogicalChannelIdentity_r17;	/* OPTIONAL */
	Uu_RelayRLC_ChannelID_r17_t	 uu_RelayRLC_ChannelID_r17;
	long	*reestablishRLC_r17;	/* OPTIONAL */
	struct RLC_Config	*rlc_Config_r17;	/* OPTIONAL */
	struct LogicalChannelConfig	*mac_LogicalChannelConfig_r17;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Uu_RelayRLC_ChannelConfig_r17_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_reestablishRLC_r17_4;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_Uu_RelayRLC_ChannelConfig_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_Uu_RelayRLC_ChannelConfig_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_Uu_RelayRLC_ChannelConfig_r17_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "RLC-Config.h"
#include "LogicalChannelConfig.h"

#endif	/* _Uu_RelayRLC_ChannelConfig_r17_H_ */
#include <asn_internal.h>
