/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-UE-Variables"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_VarMeasIdleConfig_r16_H_
#define	_VarMeasIdleConfig_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VarMeasIdleConfig_r16__measIdleDuration_r16 {
	VarMeasIdleConfig_r16__measIdleDuration_r16_sec10	= 0,
	VarMeasIdleConfig_r16__measIdleDuration_r16_sec30	= 1,
	VarMeasIdleConfig_r16__measIdleDuration_r16_sec60	= 2,
	VarMeasIdleConfig_r16__measIdleDuration_r16_sec120	= 3,
	VarMeasIdleConfig_r16__measIdleDuration_r16_sec180	= 4,
	VarMeasIdleConfig_r16__measIdleDuration_r16_sec240	= 5,
	VarMeasIdleConfig_r16__measIdleDuration_r16_sec300	= 6,
	VarMeasIdleConfig_r16__measIdleDuration_r16_spare	= 7
} e_VarMeasIdleConfig_r16__measIdleDuration_r16;

/* Forward declarations */
struct ValidityAreaList_r16;
struct MeasIdleCarrierNR_r16;
struct MeasIdleCarrierEUTRA_r16;

/* VarMeasIdleConfig-r16 */
typedef struct VarMeasIdleConfig_r16 {
	struct VarMeasIdleConfig_r16__measIdleCarrierListNR_r16 {
		A_SEQUENCE_OF(struct MeasIdleCarrierNR_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *measIdleCarrierListNR_r16;
	struct VarMeasIdleConfig_r16__measIdleCarrierListEUTRA_r16 {
		A_SEQUENCE_OF(struct MeasIdleCarrierEUTRA_r16) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *measIdleCarrierListEUTRA_r16;
	long	 measIdleDuration_r16;
	struct ValidityAreaList_r16	*validityAreaList_r16;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VarMeasIdleConfig_r16_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_measIdleDuration_r16_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_VarMeasIdleConfig_r16;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "ValidityAreaList-r16.h"
#include "MeasIdleCarrierNR-r16.h"
#include "MeasIdleCarrierEUTRA-r16.h"

#endif	/* _VarMeasIdleConfig_r16_H_ */
#include <asn_internal.h>
