/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_VisitedPSCellInfo_r17_H_
#define	_VisitedPSCellInfo_r17_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VisitedPSCellInfo_r17__visitedCellId_r17_PR {
	VisitedPSCellInfo_r17__visitedCellId_r17_PR_NOTHING,	/* No components present */
	VisitedPSCellInfo_r17__visitedCellId_r17_PR_nr_CellId_r17,
	VisitedPSCellInfo_r17__visitedCellId_r17_PR_eutra_CellId_r17
} VisitedPSCellInfo_r17__visitedCellId_r17_PR;
typedef enum VisitedPSCellInfo_r17__visitedCellId_r17__nr_CellId_r17_PR {
	VisitedPSCellInfo_r17__visitedCellId_r17__nr_CellId_r17_PR_NOTHING,	/* No components present */
	VisitedPSCellInfo_r17__visitedCellId_r17__nr_CellId_r17_PR_cgi_Info_r17,
	VisitedPSCellInfo_r17__visitedCellId_r17__nr_CellId_r17_PR_pci_arfcn_r17
} VisitedPSCellInfo_r17__visitedCellId_r17__nr_CellId_r17_PR;
typedef enum VisitedPSCellInfo_r17__visitedCellId_r17__eutra_CellId_r17_PR {
	VisitedPSCellInfo_r17__visitedCellId_r17__eutra_CellId_r17_PR_NOTHING,	/* No components present */
	VisitedPSCellInfo_r17__visitedCellId_r17__eutra_CellId_r17_PR_cellGlobalId_r17,
	VisitedPSCellInfo_r17__visitedCellId_r17__eutra_CellId_r17_PR_pci_arfcn_r17
} VisitedPSCellInfo_r17__visitedCellId_r17__eutra_CellId_r17_PR;

/* Forward declarations */
struct CGI_Info_Logging_r16;
struct PCI_ARFCN_NR_r16;
struct CGI_InfoEUTRALogging;
struct PCI_ARFCN_EUTRA_r16;

/* VisitedPSCellInfo-r17 */
typedef struct VisitedPSCellInfo_r17 {
	struct VisitedPSCellInfo_r17__visitedCellId_r17 {
		VisitedPSCellInfo_r17__visitedCellId_r17_PR present;
		union VisitedPSCellInfo_r17__visitedCellId_r17_u {
			struct VisitedPSCellInfo_r17__visitedCellId_r17__nr_CellId_r17 {
				VisitedPSCellInfo_r17__visitedCellId_r17__nr_CellId_r17_PR present;
				union VisitedPSCellInfo_r17__visitedCellId_r17__nr_CellId_r17_u {
					struct CGI_Info_Logging_r16	*cgi_Info_r17;
					struct PCI_ARFCN_NR_r16	*pci_arfcn_r17;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *nr_CellId_r17;
			struct VisitedPSCellInfo_r17__visitedCellId_r17__eutra_CellId_r17 {
				VisitedPSCellInfo_r17__visitedCellId_r17__eutra_CellId_r17_PR present;
				union VisitedPSCellInfo_r17__visitedCellId_r17__eutra_CellId_r17_u {
					struct CGI_InfoEUTRALogging	*cellGlobalId_r17;
					struct PCI_ARFCN_EUTRA_r16	*pci_arfcn_r17;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *eutra_CellId_r17;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *visitedCellId_r17;
	long	 timeSpent_r17;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VisitedPSCellInfo_r17_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VisitedPSCellInfo_r17;
extern asn_SEQUENCE_specifics_t asn_SPC_VisitedPSCellInfo_r17_specs_1;
extern asn_TYPE_member_t asn_MBR_VisitedPSCellInfo_r17_1[2];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CGI-Info-Logging-r16.h"
#include "PCI-ARFCN-NR-r16.h"
#include "CGI-InfoEUTRALogging.h"
#include "PCI-ARFCN-EUTRA-r16.h"

#endif	/* _VisitedPSCellInfo_r17_H_ */
#include <asn_internal.h>
