/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NR-RRC-Definitions"
 * 	found in "/home/hpe/openairinterface5g/openair2/RRC/NR/MESSAGES/ASN.1/nr-rrc-17.3.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-UPER -no-gen-BER -no-gen-JER -no-gen-OER -gen-APER -no-gen-example -findirect-choice -D ./temp`
 */

#ifndef	_VisitedCellInfo_r16_H_
#define	_VisitedCellInfo_r16_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum VisitedCellInfo_r16__visitedCellId_r16_PR {
	VisitedCellInfo_r16__visitedCellId_r16_PR_NOTHING,	/* No components present */
	VisitedCellInfo_r16__visitedCellId_r16_PR_nr_CellId_r16,
	VisitedCellInfo_r16__visitedCellId_r16_PR_eutra_CellId_r16
} VisitedCellInfo_r16__visitedCellId_r16_PR;
typedef enum VisitedCellInfo_r16__visitedCellId_r16__nr_CellId_r16_PR {
	VisitedCellInfo_r16__visitedCellId_r16__nr_CellId_r16_PR_NOTHING,	/* No components present */
	VisitedCellInfo_r16__visitedCellId_r16__nr_CellId_r16_PR_cgi_Info,
	VisitedCellInfo_r16__visitedCellId_r16__nr_CellId_r16_PR_pci_arfcn_r16
} VisitedCellInfo_r16__visitedCellId_r16__nr_CellId_r16_PR;
typedef enum VisitedCellInfo_r16__visitedCellId_r16__eutra_CellId_r16_PR {
	VisitedCellInfo_r16__visitedCellId_r16__eutra_CellId_r16_PR_NOTHING,	/* No components present */
	VisitedCellInfo_r16__visitedCellId_r16__eutra_CellId_r16_PR_cellGlobalId_r16,
	VisitedCellInfo_r16__visitedCellId_r16__eutra_CellId_r16_PR_pci_arfcn_r16
} VisitedCellInfo_r16__visitedCellId_r16__eutra_CellId_r16_PR;

/* Forward declarations */
struct CGI_Info_Logging_r16;
struct PCI_ARFCN_NR_r16;
struct CGI_InfoEUTRA;
struct PCI_ARFCN_EUTRA_r16;
struct VisitedPSCellInfoList_r17;

/* VisitedCellInfo-r16 */
typedef struct VisitedCellInfo_r16 {
	struct VisitedCellInfo_r16__visitedCellId_r16 {
		VisitedCellInfo_r16__visitedCellId_r16_PR present;
		union VisitedCellInfo_r16__visitedCellId_r16_u {
			struct VisitedCellInfo_r16__visitedCellId_r16__nr_CellId_r16 {
				VisitedCellInfo_r16__visitedCellId_r16__nr_CellId_r16_PR present;
				union VisitedCellInfo_r16__visitedCellId_r16__nr_CellId_r16_u {
					struct CGI_Info_Logging_r16	*cgi_Info;
					struct PCI_ARFCN_NR_r16	*pci_arfcn_r16;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *nr_CellId_r16;
			struct VisitedCellInfo_r16__visitedCellId_r16__eutra_CellId_r16 {
				VisitedCellInfo_r16__visitedCellId_r16__eutra_CellId_r16_PR present;
				union VisitedCellInfo_r16__visitedCellId_r16__eutra_CellId_r16_u {
					struct CGI_InfoEUTRA	*cellGlobalId_r16;
					struct PCI_ARFCN_EUTRA_r16	*pci_arfcn_r16;
				} choice;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *eutra_CellId_r16;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *visitedCellId_r16;
	long	 timeSpent_r16;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	struct VisitedCellInfo_r16__ext1 {
		struct VisitedPSCellInfoList_r17	*visitedPSCellInfoListReport_r17;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ext1;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VisitedCellInfo_r16_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VisitedCellInfo_r16;
extern asn_SEQUENCE_specifics_t asn_SPC_VisitedCellInfo_r16_specs_1;
extern asn_TYPE_member_t asn_MBR_VisitedCellInfo_r16_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "CGI-Info-Logging-r16.h"
#include "PCI-ARFCN-NR-r16.h"
#include "CGI-InfoEUTRA.h"
#include "PCI-ARFCN-EUTRA-r16.h"
#include "VisitedPSCellInfoList-r17.h"

#endif	/* _VisitedCellInfo_r16_H_ */
#include <asn_internal.h>
